# -*- coding: utf-8 -*-
"""Copy of stress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxDLkwblAD1PuGPLACkHWU2Y8aq9nDfC
"""





"""# Garmin stress trends using [Garth](https://github.com/matin/garth) and Matplotlib"""





"""## Setup

Start by installing and importing Garth
"""



# Commented out IPython magic to ensure Python compatibility.
# %pip install garth >& /dev/null

import garth

"""Define Garth access token location to save and resume sessions"""

GARTH_HOME = "drive/MyDrive/garth"

"""Mount Drive for saving and resuming sessions"""

from google.colab import drive
drive.mount("/content/drive")

"""Attemt to resume session. If resuming the session fails or the path set for `GARTH_HOME` doesn't exist, log in. In both cases, save the new / updated session for future use."""

from garth.exc import GarthException
from getpass import getpass

try:
    garth.resume(GARTH_HOME)
    garth.client.username
except (FileNotFoundError, GarthException):
    email = input("Email: ")
    password = getpass("Password: ")
    garth.client.login(email, password)

garth.save(GARTH_HOME)













"""## Weekly stress

Get the most recent week.
"""

garth.WeeklyStress.list()[0]

"""Get the last two years."""

weekly_stress = garth.WeeklyStress.list(period=104)

"""Use Pandas and Matplotlib with Seaborn styling to graph"""

import pandas as pd
import seaborn as sns
import matplotlib.dates as mdates
from matplotlib import pyplot as plt

df = pd.DataFrame(weekly_stress).sort_values("calendar_date")

sns.set_theme()

plt.figure(figsize=(10, 6))

sns.lineplot(x=df["calendar_date"], y=df["value"])

plt.gca().xaxis.set_major_locator(mdates.MonthLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))

plt.xticks(rotation=45)

plt.xlabel(None)
plt.ylabel(None)
plt.title("Average Weekly Stress")

plt.show()

"""## Daily stress trends

Retrieve daily averages by week. This takes a while to run.

Get yesterday's stress levels.
"""

from datetime import date, timedelta

garth.DailyStress.list(date.today() - timedelta(days=1))[0]

"""Get up to the last three years."""

daily_stress = garth.DailyStress.list(period=365 * 3)

"""Daily stats are going to have a *lot* of noise, so let's also graph the 28-day rolling average."""

import seaborn as sns
import matplotlib.dates as mdates
from matplotlib import pyplot as plt

sns.set_theme()

df = pd.DataFrame(daily_stress)
df.set_index("calendar_date", inplace=True)

df["rolling_avg"] = df["overall_stress_level"].rolling(window=28).mean()

plt.figure(figsize=(10, 6))

sns.scatterplot(
    x=df.index,
    y=df["overall_stress_level"],
    color="skyblue",
    label="Daily Stress Level"
)

sns.lineplot(
    x=df.index,
    y=df["rolling_avg"],
    color="r",
    label="28-day Rolling Average of Stress"
)

plt.gca().xaxis.set_major_locator(mdates.MonthLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))

plt.xticks(rotation=45)
plt.xlim(df.index.min(), df.index.max())
plt.xlabel(None)
plt.ylabel(None)
plt.title("Overall Stress Level Over Time")
plt.legend()

plt.show()

"""We can also use `seasonal_decompose` to look at the 28-day trend."""

from statsmodels.tsa.seasonal import seasonal_decompose

result = seasonal_decompose(
    df["overall_stress_level"], model="additive", period=28
)
trend = result.trend.dropna()

min_date = df.index.min()
max_date = df.index.max()

def plot_subplot(ax, x, y, title, color, plot_type="line"):
    if plot_type == "line":
        sns.lineplot(ax=ax, x=x, y=y, color=color)
    elif plot_type == 'scatter':
        sns.scatterplot(ax=ax, x=x, y=y, color=color)

    ax.set_title(title)
    ax.set_xlim(min_date, max_date)
    ax.set_xlabel(None)
    ax.set_ylabel(None)
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    ax.tick_params(axis="x", rotation=45)

fig, axes = plt.subplots(2, 1, figsize=(15, 6))

plot_subplot(
    axes[0], df.index, df["overall_stress_level"],
    "Daily Stress Level", "skyblue", plot_type='scatter'
)
plot_subplot(axes[1], trend.index, trend, "28-Day Trend", "r")

plt.tight_layout()
plt.show()