{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Dim_Date",
        "lineageTag": "e96a855d-a1ec-43c1-8dd5-7508901a7540",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "2751619b-4d41-4925-954a-339da093729c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Year]",
            "formatString": "0",
            "lineageTag": "6ca35a6a-757b-449f-9819-547fca0af02f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNo",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[MonthNo]",
            "formatString": "0",
            "lineageTag": "0b6a0a27-fd68-4203-8c01-252c58c143b6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Month]",
            "lineageTag": "175254f1-b98b-454c-a57e-e0eb49b9f198",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YearMonth",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[YearMonth]",
            "lineageTag": "cc874aa5-25ff-45bd-967e-844fa8e810b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Quarter]",
            "lineageTag": "1cf77474-d863-40b1-8b0d-0f5538334c80",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dim_Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "ADDCOLUMNS(",
                "    CALENDAR(",
                "        DATE(2017,1,1),",
                "        DATE(2035,12,31)",
                "    ),",
                "    \"Year\", YEAR([Date]),",
                "    \"MonthNo\", MONTH([Date]),",
                "    \"Month\", FORMAT([Date], \"MMM\"),",
                "    \"YearMonth\", FORMAT([Date], \"YYYY-MM\"),",
                "    \"Quarter\", \"Q\" & FORMAT([Date], \"Q\")",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Latest Selected Date",
            "expression": "MAX(Dim_Date[Date])",
            "formatString": "General Date",
            "displayFolder": "_Common",
            "lineageTag": "835125cc-8765-4e29-89f3-509c1fcb204a"
          },
          {
            "name": "Previous Selected Date",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Dim_Date[Date]),",
              "    FILTER(",
              "        ALLSELECTED(Dim_Date[Date]),",
              "        Dim_Date[Date] < [Latest Selected Date]",
              "    )",
              ")"
            ],
            "formatString": "General Date",
            "displayFolder": "_Common",
            "lineageTag": "1d76d620-cc92-4e72-928e-fbe36ae8926e"
          },
          {
            "name": "Test Count",
            "expression": "COUNTROWS(VALUES(Dim_Date[Date]))",
            "formatString": "0",
            "displayFolder": "_Common",
            "lineageTag": "aeb7b888-31a7-45ba-a9be-8f8a4ea41aa8"
          },
          {
            "name": "Days Between Latest And Previous Test",
            "expression": "DATEDIFF([Previous Selected Date], [Latest Selected Date], DAY)",
            "formatString": "0",
            "displayFolder": "_Common",
            "lineageTag": "ea67d2cf-106e-43f3-8f22-065243c60ea1"
          },
          {
            "name": "Dim_Profile",
            "expression": [
              "",
              "DATATABLE(",
              "    \"ProfileKey\", STRING,",
              "    \"ProfileName\", STRING,",
              "    {",
              "        {\"LIPID\", \"Lipidemic\"},",
              "        {\"ENDO\", \"Endocrinology\"}",
              "    }",
              ")"
            ],
            "lineageTag": "3816c414-da3e-4c1f-92d8-eef0923a4130"
          },
          {
            "name": "Latest Selected Calendar Date",
            "expression": "MAX(Dim_Date[Date])",
            "formatString": "yyyy-mm-dd",
            "displayFolder": "_Common",
            "lineageTag": "c17cc6e1-daa5-4ee6-be56-8467fc84375d"
          },
          {
            "name": "Previous Selected Calendar Date",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Dim_Date[Date]),",
              "    FILTER(",
              "        ALLSELECTED(Dim_Date[Date]),",
              "        Dim_Date[Date] < [Latest Selected Calendar Date]",
              "    )",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "_Common",
            "lineageTag": "5e2ae2a4-7af9-497a-bcc6-db3fae32657b"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a5b26acb453f4a588699dea5e2a2907c"
          }
        ]
      },
      {
        "name": "Fact_EndoMetrics",
        "lineageTag": "01b6dba5-6243-4c12-89e4-4eba35c7610b",
        "columns": [
          {
            "name": "exam_date",
            "dataType": "dateTime",
            "sourceColumn": "exam_date",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "cf16c07d-f4f1-4986-9cbe-52ffc030121f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "glucose_for_calc",
            "dataType": "double",
            "sourceColumn": "glucose_for_calc",
            "lineageTag": "75e5fede-f87c-4a92-a1ad-381c1e11947b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "fasting_insulin",
            "dataType": "double",
            "sourceColumn": "fasting_insulin",
            "lineageTag": "91c6aef7-e560-485c-a3b2-c3e828d177b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hba1c",
            "dataType": "double",
            "sourceColumn": "hba1c",
            "lineageTag": "57f1c09d-12b4-4045-a47e-e651eb4213a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh",
            "dataType": "double",
            "sourceColumn": "tsh",
            "lineageTag": "6385a2ca-2c97-4374-a3c1-f4ef08a45891",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "free_t4",
            "dataType": "double",
            "sourceColumn": "free_t4",
            "lineageTag": "24d4cb06-001c-4026-a06f-cb20ce5dd3d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "vitamin_d_25_oh",
            "dataType": "double",
            "sourceColumn": "vitamin_d_25_oh",
            "lineageTag": "c5a99b54-5426-414e-a118-f41a7ce0900d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "homa_ir",
            "dataType": "double",
            "sourceColumn": "homa_ir",
            "lineageTag": "bfda6fac-7d30-4b87-9d05-ca77dfd74692",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "quicki",
            "dataType": "double",
            "sourceColumn": "quicki",
            "lineageTag": "99c56a41-ccaa-42ab-be68-416a87e47306",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "eag_mgdl",
            "dataType": "double",
            "sourceColumn": "eag_mgdl",
            "lineageTag": "aab79144-77ca-4ebc-b9b9-03891ac9da51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_free_t4_ratio",
            "dataType": "double",
            "sourceColumn": "tsh_free_t4_ratio",
            "lineageTag": "35a96161-116d-4583-bcaa-578370ad2532",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "homa_ir_interpretation",
            "dataType": "string",
            "sourceColumn": "homa_ir_interpretation",
            "lineageTag": "7eba773d-efdf-4250-97f1-5ef87cfe92d1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "quicki_interpretation",
            "dataType": "string",
            "sourceColumn": "quicki_interpretation",
            "lineageTag": "79affbb2-1a25-4f84-b369-55bf33440c42",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "eag_interpretation",
            "dataType": "string",
            "sourceColumn": "eag_interpretation",
            "lineageTag": "e61f9f31-07de-43d7-8c66-a9cdc42c9307",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "vitamin_d_status",
            "dataType": "string",
            "sourceColumn": "vitamin_d_status",
            "lineageTag": "348c4a8f-aa3e-47dc-a6a5-f8c46e49134a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "glucose_for_calc_prev",
            "dataType": "double",
            "sourceColumn": "glucose_for_calc_prev",
            "lineageTag": "2bf78d3e-9c57-4ef1-a09a-f6fa14b4162f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "glucose_for_calc_delta",
            "dataType": "double",
            "sourceColumn": "glucose_for_calc_delta",
            "lineageTag": "fe2517b7-a09b-42b4-90f1-f784fd453bad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "glucose_for_calc_pct_change",
            "dataType": "double",
            "sourceColumn": "glucose_for_calc_pct_change",
            "lineageTag": "5022bae0-4a06-42a8-9595-46e67dd27779",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "glucose_for_calc_rolling3",
            "dataType": "double",
            "sourceColumn": "glucose_for_calc_rolling3",
            "lineageTag": "411e879e-dc04-4b77-89c0-b632fd32812e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "fasting_insulin_prev",
            "dataType": "double",
            "sourceColumn": "fasting_insulin_prev",
            "lineageTag": "f90e89b1-7639-47e3-9076-4a3dea080255",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "fasting_insulin_delta",
            "dataType": "double",
            "sourceColumn": "fasting_insulin_delta",
            "lineageTag": "76d1beea-a722-4c9f-9fb4-d1120887980a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "fasting_insulin_pct_change",
            "dataType": "double",
            "sourceColumn": "fasting_insulin_pct_change",
            "lineageTag": "be02c200-6bbe-4f5c-ac1c-1c83a4d94353",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "fasting_insulin_rolling3",
            "dataType": "double",
            "sourceColumn": "fasting_insulin_rolling3",
            "lineageTag": "76cde3a3-a130-407a-9a3c-08265ae10d78",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hba1c_prev",
            "dataType": "double",
            "sourceColumn": "hba1c_prev",
            "lineageTag": "6524530a-8ccb-4957-ab38-32beb1357878",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hba1c_delta",
            "dataType": "double",
            "sourceColumn": "hba1c_delta",
            "lineageTag": "d9c21861-3edf-4afa-8ba4-67af58ac7f99",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hba1c_pct_change",
            "dataType": "double",
            "sourceColumn": "hba1c_pct_change",
            "lineageTag": "7894f1d9-0048-4751-b487-6cb4ce42e84a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hba1c_rolling3",
            "dataType": "double",
            "sourceColumn": "hba1c_rolling3",
            "lineageTag": "27fa61e4-011f-4422-a7aa-1ef67777df0f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_prev",
            "dataType": "double",
            "sourceColumn": "tsh_prev",
            "lineageTag": "916d642b-35f7-473a-bfe2-88ffb79da361",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_delta",
            "dataType": "double",
            "sourceColumn": "tsh_delta",
            "lineageTag": "c0038d15-fd28-4818-a6ac-d82222affce6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_pct_change",
            "dataType": "double",
            "sourceColumn": "tsh_pct_change",
            "lineageTag": "b39008dd-fe9c-4973-ab59-356fa7ab0b62",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_rolling3",
            "dataType": "double",
            "sourceColumn": "tsh_rolling3",
            "lineageTag": "fe55d44f-cc85-4480-922b-ac13f18cc528",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "free_t4_prev",
            "dataType": "double",
            "sourceColumn": "free_t4_prev",
            "lineageTag": "6f4971c1-01ce-4509-ba75-0ffb2ac1047c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "free_t4_delta",
            "dataType": "double",
            "sourceColumn": "free_t4_delta",
            "lineageTag": "e2b1145b-ca35-4237-8f8e-8af94c8954e2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "free_t4_pct_change",
            "dataType": "double",
            "sourceColumn": "free_t4_pct_change",
            "lineageTag": "9470eebf-03a6-43dc-a68e-d98e52343444",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "free_t4_rolling3",
            "dataType": "double",
            "sourceColumn": "free_t4_rolling3",
            "lineageTag": "33193181-d209-4945-b778-bfc96467f95f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "vitamin_d_25_oh_prev",
            "dataType": "double",
            "sourceColumn": "vitamin_d_25_oh_prev",
            "lineageTag": "31762e73-dce3-4f4b-b8c6-8dd13dfec375",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "vitamin_d_25_oh_delta",
            "dataType": "double",
            "sourceColumn": "vitamin_d_25_oh_delta",
            "lineageTag": "d98ceef0-5e0f-427a-9743-092547d47af3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "vitamin_d_25_oh_pct_change",
            "dataType": "double",
            "sourceColumn": "vitamin_d_25_oh_pct_change",
            "lineageTag": "477fbf8d-55c8-4d39-a617-e44093633d73",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "vitamin_d_25_oh_rolling3",
            "dataType": "double",
            "sourceColumn": "vitamin_d_25_oh_rolling3",
            "lineageTag": "c8f7dc0b-084d-4b12-b6d0-c8126df2ce96",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "homa_ir_prev",
            "dataType": "double",
            "sourceColumn": "homa_ir_prev",
            "lineageTag": "b554310c-df09-49c3-ac0a-cdfa5a28300d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "homa_ir_delta",
            "dataType": "double",
            "sourceColumn": "homa_ir_delta",
            "lineageTag": "e6b08b0b-835e-4a85-a5d9-bd352c1604cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "homa_ir_pct_change",
            "dataType": "double",
            "sourceColumn": "homa_ir_pct_change",
            "lineageTag": "ac298917-7cbb-408e-b7a8-c26260c080b6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "homa_ir_rolling3",
            "dataType": "double",
            "sourceColumn": "homa_ir_rolling3",
            "lineageTag": "024de820-4d40-43a9-b41a-f779e0d8bf8c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "quicki_prev",
            "dataType": "double",
            "sourceColumn": "quicki_prev",
            "lineageTag": "776e6e2d-7fe0-4cd2-bf0e-c59ac7aa3bd0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "quicki_delta",
            "dataType": "double",
            "sourceColumn": "quicki_delta",
            "lineageTag": "35a19a27-aed7-451a-b08c-32c7dfa5b3ee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "quicki_pct_change",
            "dataType": "double",
            "sourceColumn": "quicki_pct_change",
            "lineageTag": "71ea35de-a071-40d0-b452-187e00e01260",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "quicki_rolling3",
            "dataType": "double",
            "sourceColumn": "quicki_rolling3",
            "lineageTag": "bdb95131-15dd-40de-a529-ac2c78fed437",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "eag_mgdl_prev",
            "dataType": "double",
            "sourceColumn": "eag_mgdl_prev",
            "lineageTag": "a27921df-6d83-46aa-85b3-206adf937ccd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "eag_mgdl_delta",
            "dataType": "double",
            "sourceColumn": "eag_mgdl_delta",
            "lineageTag": "51a38bb0-6908-405f-9792-2e9c9e1cf9f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "eag_mgdl_pct_change",
            "dataType": "double",
            "sourceColumn": "eag_mgdl_pct_change",
            "lineageTag": "f6294d32-7e0a-4653-910b-65d63454b54a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "eag_mgdl_rolling3",
            "dataType": "double",
            "sourceColumn": "eag_mgdl_rolling3",
            "lineageTag": "f681855e-6765-4835-9d5c-bba6375bc01a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_free_t4_ratio_prev",
            "dataType": "double",
            "sourceColumn": "tsh_free_t4_ratio_prev",
            "lineageTag": "77cb9b8a-c71f-4606-abf6-0b5f6ba2568b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_free_t4_ratio_delta",
            "dataType": "double",
            "sourceColumn": "tsh_free_t4_ratio_delta",
            "lineageTag": "01658da1-e8fb-4f1c-9d57-eb8a582a1396",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_free_t4_ratio_pct_change",
            "dataType": "double",
            "sourceColumn": "tsh_free_t4_ratio_pct_change",
            "lineageTag": "2a588071-7ee0-4dd9-93fa-11e71cc4a2bc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tsh_free_t4_ratio_rolling3",
            "dataType": "double",
            "sourceColumn": "tsh_free_t4_ratio_rolling3",
            "lineageTag": "eeaa71a3-8c5d-4c64-be4d-b46c5401136d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "has_core_endo",
            "dataType": "double",
            "sourceColumn": "has_core_endo",
            "lineageTag": "7d443176-295c-4e4c-a457-de701fb482e2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "is_complete_metabolic_ir",
            "dataType": "double",
            "sourceColumn": "is_complete_metabolic_ir",
            "lineageTag": "7271e256-938d-450e-8d4d-9d782bcbb30f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "record_quality_note",
            "dataType": "string",
            "sourceColumn": "record_quality_note",
            "lineageTag": "fa6cb492-5356-41f1-85d2-ceaee5782335",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "created_at",
            "dataType": "dateTime",
            "sourceColumn": "created_at",
            "formatString": "General Date",
            "lineageTag": "91edaef7-9bf3-42b7-8012-55f234c112c1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "updated_at",
            "dataType": "dateTime",
            "sourceColumn": "updated_at",
            "formatString": "General Date",
            "lineageTag": "6a663c49-111b-478a-9186-a02a2dd00b61",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "has_core_endocrine",
            "dataType": "double",
            "sourceColumn": "has_core_endocrine",
            "lineageTag": "061d0048-c16d-447c-8b85-f68936da71fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "is_complete_profile",
            "dataType": "double",
            "sourceColumn": "is_complete_profile",
            "lineageTag": "610db126-8f02-4e5b-a6fd-b6602cf58c8e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_EndoMetrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"dsn=bllod_raw\", [HierarchicalNavigation=true]),",
                "    endo_metrics_Table = Source{[Name=\"endo_metrics\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(endo_metrics_Table,{{\"exam_date\", type date}, {\"created_at\", type datetime}, {\"updated_at\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Endo Latest Glucose",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[glucose_for_calc]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest Glucose Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "2def5c6e-de5a-435d-952b-7170ecb1e766"
          },
          {
            "name": "Endo Previous Glucose",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[glucose_for_calc]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous Glucose Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "9f64f5c5-aa49-485a-9223-5f33c91e8129"
          },
          {
            "name": "Endo Glucose Delta",
            "expression": "[Endo Latest Glucose] - [Endo Previous Glucose]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "4f38a9ac-68fe-41f1-8a7c-f3c76cf424a4"
          },
          {
            "name": "Endo Glucose Delta %",
            "expression": "DIVIDE([Endo Glucose Delta], [Endo Previous Glucose])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "bdbdc163-9ac6-4776-8f1c-799ad78446e7"
          },
          {
            "name": "Endo Glucose Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[glucose_for_calc])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[glucose_for_calc]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "45401005-af74-4b24-9bb6-fae9221367d3"
          },
          {
            "name": "Endo Latest Fasting Insulin",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[fasting_insulin]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest Fasting Insulin Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "1be40d9c-8625-43ac-a755-2a5960b2d7ff"
          },
          {
            "name": "Endo Previous Fasting Insulin",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[fasting_insulin]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous Fasting Insulin Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "2614c447-269b-4bd9-bb3c-03581a64bcf0"
          },
          {
            "name": "Endo Fasting Insulin Delta",
            "expression": "[Endo Latest Fasting Insulin] - [Endo Previous Fasting Insulin]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "6bc2560d-5b64-4c2a-887b-aa26660d3b16"
          },
          {
            "name": "Endo Fasting Insulin Delta %",
            "expression": "DIVIDE([Endo Fasting Insulin Delta], [Endo Previous Fasting Insulin])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "6be39db8-726f-445f-9569-12b5a0f95377"
          },
          {
            "name": "Endo Fasting Insulin Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[fasting_insulin])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[fasting_insulin]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "4ed1f6d0-1063-4484-a6fa-292faa46f805"
          },
          {
            "name": "Endo Latest HbA1c",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[hba1c]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest HbA1c Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "ac0a30f0-33b3-46db-92f1-80de4a535d76"
          },
          {
            "name": "Endo Previous HbA1c",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[hba1c]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous HbA1c Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "6e7fa8d6-3e5c-4a69-bd81-3dd307d3ea09"
          },
          {
            "name": "Endo HbA1c Delta",
            "expression": "[Endo Latest HbA1c] - [Endo Previous HbA1c]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "8f434043-0c4a-41fa-a385-9f5eb981d68a"
          },
          {
            "name": "Endo HbA1c Delta %",
            "expression": "DIVIDE([Endo HbA1c Delta], [Endo Previous HbA1c])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "3b504221-d5b2-4103-9f14-109ad32802a4"
          },
          {
            "name": "Endo HbA1c Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[hba1c])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[hba1c]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "26509c0b-250b-43f4-863d-4b57b98479b9"
          },
          {
            "name": "Endo Latest eAG",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[eag_mgdl]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest eAG Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "ce72b3dc-65c9-4855-9d69-ce859b8270df"
          },
          {
            "name": "Endo Previous eAG",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[eag_mgdl]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous eAG Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "15962bce-b505-4fd7-8d97-c6391f86799c"
          },
          {
            "name": "Endo eAG Delta",
            "expression": "[Endo Latest eAG] - [Endo Previous eAG]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "9fefd7da-2a38-4425-9c49-d919856fc575"
          },
          {
            "name": "Endo eAG Delta %",
            "expression": "DIVIDE([Endo eAG Delta], [Endo Previous eAG])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "f0796da5-bd92-4211-ac9a-cdc0b48ced92"
          },
          {
            "name": "Endo eAG Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[eag_mgdl])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[eag_mgdl]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "9bbb37a1-8768-4730-9901-b2d013ecc0cf"
          },
          {
            "name": "Endo Latest HOMA-IR",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[homa_ir]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest HOMA-IR Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "edd98df7-ed0e-4661-a7c4-a2f95de83087"
          },
          {
            "name": "Endo Previous HOMA-IR",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[homa_ir]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous HOMA-IR Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "52fdf11f-3880-4057-b528-c1bd0a29df0a"
          },
          {
            "name": "Endo HOMA-IR Delta",
            "expression": "[Endo Latest HOMA-IR] - [Endo Previous HOMA-IR]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "85b3b225-eb0e-4848-9667-0ef12b0d9190"
          },
          {
            "name": "Endo HOMA-IR Delta %",
            "expression": "DIVIDE([Endo HOMA-IR Delta], [Endo Previous HOMA-IR])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "e9980c5f-2e4c-4c32-9b76-17947248d25c"
          },
          {
            "name": "Endo HOMA-IR Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[homa_ir])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[homa_ir]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "941e6b28-a175-4017-b203-7f3a46917e5d"
          },
          {
            "name": "Endo Latest QUICKI",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[quicki]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest QUICKI Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "75178061-62cd-495d-908a-4539dd5dac9b"
          },
          {
            "name": "Endo Previous QUICKI",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[quicki]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous QUICKI Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "65b16a0c-3217-45ba-b60c-a91d1e37e699"
          },
          {
            "name": "Endo QUICKI Delta",
            "expression": "[Endo Latest QUICKI] - [Endo Previous QUICKI]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "0716f22d-0bdc-4413-9c0c-902b74311f8f"
          },
          {
            "name": "Endo QUICKI Delta %",
            "expression": "DIVIDE([Endo QUICKI Delta], [Endo Previous QUICKI])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "a3be5cbf-d64e-4b1f-8b08-7da498c65ca1"
          },
          {
            "name": "Endo QUICKI Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[quicki])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[quicki]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "71787345-22bf-4971-88a2-73c608022b12"
          },
          {
            "name": "Endo Latest TSH",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[tsh]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest TSH Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "aa55bcd7-6acc-4d8d-bf21-c008a55a4fb8"
          },
          {
            "name": "Endo Previous TSH",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[tsh]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous TSH Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "2b139465-9595-448f-9018-957b131827c0"
          },
          {
            "name": "Endo TSH Delta",
            "expression": "[Endo Latest TSH] - [Endo Previous TSH]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "57c3d1ae-5489-4172-be7e-eed83a6d8ec4"
          },
          {
            "name": "Endo TSH Delta %",
            "expression": "DIVIDE([Endo TSH Delta], [Endo Previous TSH])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "c0d73a24-13c5-4da4-8a5f-64afce842f07"
          },
          {
            "name": "Endo TSH Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[tsh])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[tsh]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "07b8a772-3be7-435d-a8a0-3d495ca406f0"
          },
          {
            "name": "Endo Latest Free T4",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[free_t4]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest Free T4 Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "96bb7241-4109-417a-84f4-e42d5e8a1412"
          },
          {
            "name": "Endo Previous Free T4",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[free_t4]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous Free T4 Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "d54c897a-42c7-4549-b572-1122fdd7def5"
          },
          {
            "name": "Endo Free T4 Delta",
            "expression": "[Endo Latest Free T4] - [Endo Previous Free T4]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "a878f61c-8569-4b4d-88b8-cad82fe21d13"
          },
          {
            "name": "Endo Free T4 Delta %",
            "expression": "DIVIDE([Endo Free T4 Delta], [Endo Previous Free T4])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "ee12165f-7373-4880-8b6f-aab58d60ea3f"
          },
          {
            "name": "Endo Free T4 Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[free_t4])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[free_t4]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "14c3b4f4-7a58-4996-91e1-c737f4530c0e"
          },
          {
            "name": "Endo Latest TSH/Free T4 Ratio",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[tsh_free_t4_ratio]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest TSH/Free T4 Ratio Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "3c5abab2-33cf-4d88-a91d-4ee21281b316"
          },
          {
            "name": "Endo Previous TSH/Free T4 Ratio",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[tsh_free_t4_ratio]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous TSH/Free T4 Ratio Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "31631d53-c357-4e5c-88b3-798bb46f26c8"
          },
          {
            "name": "Endo TSH/Free T4 Ratio Delta",
            "expression": "[Endo Latest TSH/Free T4 Ratio] - [Endo Previous TSH/Free T4 Ratio]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "f4f2543a-1130-4829-a3d5-71f41dfc8986"
          },
          {
            "name": "Endo TSH/Free T4 Ratio Delta %",
            "expression": "DIVIDE([Endo TSH/Free T4 Ratio Delta], [Endo Previous TSH/Free T4 Ratio])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "3cef3e19-07a8-44e1-a916-ef5e905bf404"
          },
          {
            "name": "Endo TSH/Free T4 Ratio Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[tsh_free_t4_ratio])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[tsh_free_t4_ratio]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "9dad1c6e-4d1a-4ed4-85c7-090662488ef8"
          },
          {
            "name": "Endo Latest Vitamin D",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[vitamin_d_25_oh]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Latest Vitamin D Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Latest",
            "lineageTag": "35b4e3a3-dae7-42dc-93e0-96e0e34aadd5"
          },
          {
            "name": "Endo Previous Vitamin D",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_EndoMetrics[vitamin_d_25_oh]),",
              "    FILTER(",
              "        ALL(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] = [Endo Previous Vitamin D Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Previous",
            "lineageTag": "687eecd1-f247-4741-a9d3-c0f63aa7700e"
          },
          {
            "name": "Endo Vitamin D Delta",
            "expression": "[Endo Latest Vitamin D] - [Endo Previous Vitamin D]",
            "formatString": "0.00",
            "displayFolder": "Endo - Delta",
            "lineageTag": "4119179b-32c6-4321-ba30-46d9d71daf98"
          },
          {
            "name": "Endo Vitamin D Delta %",
            "expression": "DIVIDE([Endo Vitamin D Delta], [Endo Previous Vitamin D])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Endo - Delta %",
            "lineageTag": "ce0ecb78-2656-4665-a809-58f08f80874c"
          },
          {
            "name": "Endo Vitamin D Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_EndoMetrics),",
              "            NOT ISBLANK(Fact_EndoMetrics[vitamin_d_25_oh])",
              "        ),",
              "        Fact_EndoMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_EndoMetrics[vitamin_d_25_oh]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - Rolling 3",
            "lineageTag": "c2350e5f-a12c-44bb-b10a-d3ca240650d8"
          },
          {
            "name": "Endo Glucose Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo Glucose Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "e7ae2a2e-7a97-4d94-8a4b-3ce84bdc722c"
          },
          {
            "name": "Endo Fasting Insulin Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo Fasting Insulin Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "074e06d5-ada2-4e71-bc50-efd21a0e929a"
          },
          {
            "name": "Endo HbA1c Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo HbA1c Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "81cd06a6-10d5-412e-bf15-bbfc2f8214c9"
          },
          {
            "name": "Endo eAG Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo eAG Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "0287359c-cbca-4719-861d-3752382185eb"
          },
          {
            "name": "Endo HOMA-IR Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo HOMA-IR Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "8c4baea6-2913-45c1-a07c-fab5e4a45a35"
          },
          {
            "name": "Endo QUICKI Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo QUICKI Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d > 0, \"Improving\",",
              "    d < 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "e025ae11-e95a-49f2-9aa2-c18deba49267"
          },
          {
            "name": "Endo TSH Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo TSH Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "812a6bd4-5067-4223-bd82-cd7f7148e709"
          },
          {
            "name": "Endo Free T4 Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo Free T4 Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d > 0, \"Improving\",",
              "    d < 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "2aa146ae-125f-45c4-aae0-cb25e4890a0f"
          },
          {
            "name": "Endo TSH/Free T4 Ratio Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo TSH/Free T4 Ratio Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "77af5f70-7fcd-4455-a07b-046c2e72f979"
          },
          {
            "name": "Endo Vitamin D Trend Direction",
            "expression": [
              "",
              "VAR d = [Endo Vitamin D Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d > 0, \"Improving\",",
              "    d < 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Endo - Trend",
            "lineageTag": "f74e0cf8-6a5f-450b-8fb0-de64e14bf8c8"
          },
          {
            "name": "Endo HOMA-IR Score",
            "expression": [
              "",
              "VAR x = [Endo Latest HOMA-IR]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 2, 1,",
              "    x < 3, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Endo - KPI",
            "lineageTag": "ac98348f-780b-470f-8207-fd288b8a2897"
          },
          {
            "name": "Endo QUICKI Score",
            "expression": [
              "",
              "VAR x = [Endo Latest QUICKI]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x >= 0.35, 1,",
              "    x >= 0.30, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Endo - KPI",
            "lineageTag": "f8fb74f9-20fa-4f94-aec6-6fd568849fd1"
          },
          {
            "name": "Endo Vitamin D Score",
            "expression": [
              "",
              "VAR x = [Endo Latest Vitamin D]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 20, 3,",
              "    x < 30, 2,",
              "    x <= 100, 1,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Endo - KPI",
            "lineageTag": "fd2d7441-d3d0-4b11-a0bc-48e8b9fab84f"
          },
          {
            "name": "Endo HbA1c Score",
            "expression": [
              "",
              "VAR x = [Endo Latest HbA1c]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 5.7, 1,",
              "    x < 6.5, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Endo - KPI",
            "lineageTag": "39e9c3c4-9841-4cd6-89c0-25b85b76128f"
          },
          {
            "name": "Endo Glucose Score",
            "expression": [
              "",
              "VAR x = [Endo Latest Glucose]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 100, 1,",
              "    x < 126, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Endo - KPI",
            "lineageTag": "37402ed2-e06d-4a63-974c-bddaf06cf86c"
          },
          {
            "name": "Endo HOMA-IR Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo HOMA-IR Score],",
              "    1, \"Favorable / insulin sensitive\",",
              "    2, \"Borderline insulin resistance\",",
              "    3, \"Insulin resistance signal\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "fbe2e351-d14d-4513-aff0-285f90bbb314"
          },
          {
            "name": "Endo QUICKI Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo QUICKI Score],",
              "    1, \"Better insulin sensitivity\",",
              "    2, \"Borderline\",",
              "    3, \"Lower insulin sensitivity\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "6025cfbc-730f-4056-865e-5309097c0006"
          },
          {
            "name": "Endo Vitamin D Indicator",
            "expression": [
              "",
              "VAR x = [Endo Latest Vitamin D]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 20, \"Deficient\",",
              "    x < 30, \"Insufficient\",",
              "    x <= 50, \"Sufficient\",",
              "    x <= 100, \"High / upper range\",",
              "    \"Potential excess\"",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "758f9008-ee13-42ba-80e2-5df58a271ffa"
          },
          {
            "name": "Endo HbA1c Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo HbA1c Score],",
              "    1, \"Favorable\",",
              "    2, \"Prediabetes range\",",
              "    3, \"Diabetes range\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "02aa1c78-db5c-4718-8fc8-0dca59a72535"
          },
          {
            "name": "Endo Glucose Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo Glucose Score],",
              "    1, \"Favorable\",",
              "    2, \"Impaired fasting range\",",
              "    3, \"High fasting glucose range\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "50c71481-ad84-4d93-9bcf-066ab4acda91"
          },
          {
            "name": "Endo Composite Risk Score",
            "expression": [
              "",
              "AVERAGEX(",
              "    {",
              "        [Endo HOMA-IR Score],",
              "        [Endo QUICKI Score],",
              "        [Endo Vitamin D Score],",
              "        [Endo HbA1c Score],",
              "        [Endo Glucose Score]",
              "    },",
              "    [Value]",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Endo - KPI",
            "lineageTag": "92ae1fc2-1ca1-455f-a0d9-9a6b7ee20342"
          },
          {
            "name": "Endo Composite KPI",
            "expression": [
              "",
              "VAR x = [Endo Composite Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.4, \"Favorable\",",
              "    x <= 2.1, \"Monitor\",",
              "    x <= 2.8, \"Elevated metabolic/endocrine concern\",",
              "    \"High concern\"",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "3e83e0ce-2218-4259-91fd-5731f95b33de"
          },
          {
            "name": "Endo Composite Color Hex",
            "expression": [
              "",
              "VAR x = [Endo Composite Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.4, \"#2E7D32\",",
              "    x <= 2.1, \"#F9A825\",",
              "    x <= 2.8, \"#EF6C00\",",
              "    \"#C62828\"",
              ")"
            ],
            "displayFolder": "Endo - KPI",
            "lineageTag": "fa0fe00b-e001-4251-88fc-fe6f3da7b41b"
          },
          {
            "name": "Endo HOMA-IR Stability KPI",
            "expression": "ABS([Endo Latest HOMA-IR] - [Endo HOMA-IR Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Endo - Stability",
            "lineageTag": "d8a0e75c-0942-43bd-825b-f62e2a2a6708"
          },
          {
            "name": "Endo QUICKI Stability KPI",
            "expression": "ABS([Endo Latest QUICKI] - [Endo QUICKI Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Endo - Stability",
            "lineageTag": "497e96ce-c981-4640-ad53-6c54b657c580"
          },
          {
            "name": "Endo HbA1c Stability KPI",
            "expression": "ABS([Endo Latest HbA1c] - [Endo HbA1c Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Endo - Stability",
            "lineageTag": "0abe6f14-1dc0-4784-a40a-869007741852"
          },
          {
            "name": "Endo Vitamin D Stability KPI",
            "expression": "ABS([Endo Latest Vitamin D] - [Endo Vitamin D Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Endo - Stability",
            "lineageTag": "9a175d16-0853-4cbf-87aa-f319407bea9a"
          },
          {
            "name": "Endo HOMA-IR Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo HOMA-IR Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Endo",
            "lineageTag": "c44bfd6f-1ea5-4f7f-8bea-6a242e457fad"
          },
          {
            "name": "Endo QUICKI Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo QUICKI Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Endo",
            "lineageTag": "f9025a4a-6a57-4c3e-8c08-d36f65441e0a"
          },
          {
            "name": "Endo Vitamin D Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo Vitamin D Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Endo",
            "lineageTag": "bbc1c1e8-a99b-4ff9-bd8c-52fa0655965e"
          },
          {
            "name": "Endo HbA1c Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo HbA1c Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Endo",
            "lineageTag": "59375207-5f85-445d-afd8-98ac5569fb04"
          },
          {
            "name": "Endo Glucose Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo Glucose Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Endo",
            "lineageTag": "6c6dc4f8-6961-4edb-9e90-1b1c99a9ab0c"
          },
          {
            "name": "Endo HOMA-IR Trend Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo HOMA-IR Trend Direction],",
              "    \"Improving\", \"#2E7D32\",",
              "    \"Worsening\", \"#C62828\",",
              "    \"Stable\", \"#9E9E9E\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Trend",
            "lineageTag": "5228ad6b-0197-4f99-ad48-85e3b9a2f0bf"
          },
          {
            "name": "Endo QUICKI Trend Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Endo QUICKI Trend Direction],",
              "    \"Improving\", \"#2E7D32\",",
              "    \"Worsening\", \"#C62828\",",
              "    \"Stable\", \"#9E9E9E\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Trend",
            "lineageTag": "4edb810b-4a83-41db-8b1e-b45bb4476a22"
          },
          {
            "name": "Endo Latest Glucose Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[glucose_for_calc])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "9d265dcf-c210-46d5-b1e4-aa25a78c4ad0"
          },
          {
            "name": "Endo Previous Glucose Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest Glucose Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[glucose_for_calc])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "ba4fc4ad-7c24-4951-9f16-5917a07836a2"
          },
          {
            "name": "Endo Latest Fasting Insulin Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[fasting_insulin])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "36dc99d4-8725-44f4-a216-83c02b8c430c"
          },
          {
            "name": "Endo Previous Fasting Insulin Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest Fasting Insulin Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[fasting_insulin])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "8377170d-312a-4df5-bf95-5fd43e804460"
          },
          {
            "name": "Endo Latest HbA1c Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[hba1c])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "92a9b7a1-cd48-4810-bdcb-725e3104eba5"
          },
          {
            "name": "Endo Previous HbA1c Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest HbA1c Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[hba1c])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "b41bea58-d681-4ea3-a923-d3a8e83317ed"
          },
          {
            "name": "Endo Latest eAG Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[eag_mgdl])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "e1680629-8cc9-4fe0-8a10-ac8b4eb7f5cb"
          },
          {
            "name": "Endo Previous eAG Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest eAG Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[eag_mgdl])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "fe4db926-6192-4a7a-b6e4-f99d0df61906"
          },
          {
            "name": "Endo Latest HOMA-IR Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[homa_ir])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "bc7b0057-303c-4b6d-befb-2431bfe85bdd"
          },
          {
            "name": "Endo Previous HOMA-IR Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest HOMA-IR Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[homa_ir])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "bf4c5fe8-4e67-459d-938a-54339f6cfc11"
          },
          {
            "name": "Endo Latest QUICKI Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[quicki])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "fc837f96-c6f2-4dc4-b3ee-ae1869938857"
          },
          {
            "name": "Endo Previous QUICKI Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest QUICKI Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[quicki])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "174bb705-661d-4730-b229-1a417062fb20"
          },
          {
            "name": "Endo Latest TSH Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[tsh])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "786d3264-ce77-4222-bbc4-8c71b1bc4963"
          },
          {
            "name": "Endo Previous TSH Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest TSH Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[tsh])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "899a9c13-f0fc-4980-8381-bcbbe5f9c8ec"
          },
          {
            "name": "Endo Latest Free T4 Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[free_t4])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "6108b667-3840-4623-9f4c-514a1650eac6"
          },
          {
            "name": "Endo Previous Free T4 Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest Free T4 Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[free_t4])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "5b7e0306-fa6d-472d-abff-a8279f105cbd"
          },
          {
            "name": "Endo Latest TSH/Free T4 Ratio Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[tsh_free_t4_ratio])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "99f9945b-b9df-4975-b8a1-9326f040d41b"
          },
          {
            "name": "Endo Previous TSH/Free T4 Ratio Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest TSH/Free T4 Ratio Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[tsh_free_t4_ratio])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "fd06fa74-1a62-4253-b41a-1671354cb6ff"
          },
          {
            "name": "Endo Latest Vitamin D Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        NOT ISBLANK(Fact_EndoMetrics[vitamin_d_25_oh])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "2669593b-721d-4809-b8c1-fddb1df924b6"
          },
          {
            "name": "Endo Previous Vitamin D Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_EndoMetrics),",
              "        Fact_EndoMetrics[exam_date] < [Endo Latest Vitamin D Data Date]",
              "            && NOT ISBLANK(Fact_EndoMetrics[vitamin_d_25_oh])",
              "    ),",
              "    Fact_EndoMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "4f92c669-3dfb-4b3d-8f02-2630998ddcbf"
          },
          {
            "name": "Endo Days Between Latest And Previous Test",
            "expression": "DATEDIFF([Endo Previous Glucose Data Date], [Endo Latest Glucose Data Date], DAY)",
            "formatString": "0",
            "displayFolder": "Endo - Data Dates",
            "lineageTag": "343e80f1-4724-450a-a8a3-c1dee6086677"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_LipidMetrics",
        "lineageTag": "c519e5ac-8cc0-49cf-81fd-b57895b3302d",
        "columns": [
          {
            "name": "metric_id",
            "dataType": "double",
            "sourceColumn": "metric_id",
            "lineageTag": "8964096e-80bc-4efa-b3f6-0eb164bef444",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "exam_date",
            "dataType": "dateTime",
            "sourceColumn": "exam_date",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "f9650fa8-a3a0-43e2-9bc6-8bf4b99c7686",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "total_cholesterol",
            "dataType": "double",
            "sourceColumn": "total_cholesterol",
            "lineageTag": "075f2d7c-0b73-48ad-b80e-2027d801775b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hdl",
            "dataType": "double",
            "sourceColumn": "hdl",
            "lineageTag": "c7492de3-f8f1-46d2-9f8a-7a17a3f436b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_reported",
            "dataType": "double",
            "sourceColumn": "ldl_reported",
            "lineageTag": "59acd473-e8ee-4459-b37d-70b873deb7f2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "triglycerides",
            "dataType": "double",
            "sourceColumn": "triglycerides",
            "lineageTag": "4a2b1af0-c1e7-4c29-8aae-542f20f30b75",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "reported_non_hdl",
            "dataType": "double",
            "sourceColumn": "reported_non_hdl",
            "lineageTag": "7a7ae37d-fd6d-47b5-a65b-d307c4e3364c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "lpa",
            "dataType": "double",
            "sourceColumn": "lpa",
            "lineageTag": "d624893d-1bd3-4366-a00d-64af749ffdd4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_friedewald",
            "dataType": "double",
            "sourceColumn": "ldl_friedewald",
            "lineageTag": "5b7be829-580e-41e4-8b24-c70275f17549",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_sampson",
            "dataType": "double",
            "sourceColumn": "ldl_sampson",
            "lineageTag": "dbcf8db4-c7eb-4cb8-8eaf-45c71d8484f5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_final",
            "dataType": "double",
            "sourceColumn": "ldl_final",
            "lineageTag": "48531dc9-cc0b-42de-965d-c5502c8c4c82",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_method",
            "dataType": "string",
            "sourceColumn": "ldl_method",
            "lineageTag": "29798299-2dad-41a9-a878-8122e9261e13",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "non_hdl_calc",
            "dataType": "double",
            "sourceColumn": "non_hdl_calc",
            "lineageTag": "0e190d78-9a91-4cbf-aa1e-2625b7e8ae16",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "non_hdl_final",
            "dataType": "double",
            "sourceColumn": "non_hdl_final",
            "lineageTag": "eecf5277-6830-4c2b-9b48-384a818fc5b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "non_hdl_delta_vs_reported",
            "dataType": "double",
            "sourceColumn": "non_hdl_delta_vs_reported",
            "lineageTag": "40682798-8223-4fd5-9350-c9661f983559",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tc_hdl_ratio",
            "dataType": "double",
            "sourceColumn": "tc_hdl_ratio",
            "lineageTag": "450d0462-6429-49fd-91d2-e8f9ba86f3a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_hdl_ratio",
            "dataType": "double",
            "sourceColumn": "ldl_hdl_ratio",
            "lineageTag": "c77e0310-1914-4011-a04a-45470e8c6c0c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tg_hdl_ratio",
            "dataType": "double",
            "sourceColumn": "tg_hdl_ratio",
            "lineageTag": "677270b9-c129-4585-9770-84ac52cae37f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "aip",
            "dataType": "double",
            "sourceColumn": "aip",
            "lineageTag": "44536bdf-faa9-42b9-bad5-8b024e745d60",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "remnant_cholesterol",
            "dataType": "double",
            "sourceColumn": "remnant_cholesterol",
            "lineageTag": "869e151b-164a-4293-a389-1c4cccc4bcb9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "vldl_estimated",
            "dataType": "double",
            "sourceColumn": "vldl_estimated",
            "lineageTag": "4be7f6dd-4f01-455a-8acd-4ecda63ab7f9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "cholesterol_residual_burden",
            "dataType": "double",
            "sourceColumn": "cholesterol_residual_burden",
            "lineageTag": "42e19bd6-b9f6-46ed-953f-bb123b636fac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "lpa_present",
            "dataType": "double",
            "sourceColumn": "lpa_present",
            "lineageTag": "a5ff1a31-1443-41ef-b4c6-0d6dba376145",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tg_status",
            "dataType": "string",
            "sourceColumn": "tg_status",
            "lineageTag": "50b7a74d-9cad-4df0-9057-e8c8e6fdcbee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "non_hdl_risk",
            "dataType": "string",
            "sourceColumn": "non_hdl_risk",
            "lineageTag": "e6f79e95-082d-4141-abcc-2ca5fcb35719",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "tc_hdl_risk",
            "dataType": "string",
            "sourceColumn": "tc_hdl_risk",
            "lineageTag": "0c235517-e3de-4ad1-b06a-05d2428915f6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "ldl_hdl_risk",
            "dataType": "string",
            "sourceColumn": "ldl_hdl_risk",
            "lineageTag": "a2571587-c912-4747-a47f-70751f9e0310",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "tg_hdl_risk",
            "dataType": "string",
            "sourceColumn": "tg_hdl_risk",
            "lineageTag": "3a9afe6a-849c-42a1-9799-111c17aa8c42",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "aip_risk",
            "dataType": "string",
            "sourceColumn": "aip_risk",
            "lineageTag": "124b18d7-6d1d-4f6d-acdb-706aa0cbc769",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "remnant_risk",
            "dataType": "string",
            "sourceColumn": "remnant_risk",
            "lineageTag": "052dadd5-28f1-40f0-b14b-d49e02fb3b24",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "total_cholesterol_prev",
            "dataType": "double",
            "sourceColumn": "total_cholesterol_prev",
            "lineageTag": "358a1bc0-a71c-41be-9699-7e05633112e0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_cholesterol_delta",
            "dataType": "double",
            "sourceColumn": "total_cholesterol_delta",
            "lineageTag": "5ee77b4b-b1ff-4e10-8469-f1768be5cdc6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_cholesterol_pct_change",
            "dataType": "double",
            "sourceColumn": "total_cholesterol_pct_change",
            "lineageTag": "3a3de554-83a5-40c7-bdb4-a2058ffe1f5c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_cholesterol_rolling3",
            "dataType": "double",
            "sourceColumn": "total_cholesterol_rolling3",
            "lineageTag": "a72eadf2-80a7-4d3f-8782-0a2f00b501d5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hdl_prev",
            "dataType": "double",
            "sourceColumn": "hdl_prev",
            "lineageTag": "67afa857-2bd4-4008-8d6a-d030cdde08b5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hdl_delta",
            "dataType": "double",
            "sourceColumn": "hdl_delta",
            "lineageTag": "31e1cec4-41bf-4ece-9d59-747c5cadc4b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hdl_pct_change",
            "dataType": "double",
            "sourceColumn": "hdl_pct_change",
            "lineageTag": "c31396bf-e53d-4438-ac1b-a70e690215e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "hdl_rolling3",
            "dataType": "double",
            "sourceColumn": "hdl_rolling3",
            "lineageTag": "3bb8f826-486a-4677-8901-70a5bd4266f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_final_prev",
            "dataType": "double",
            "sourceColumn": "ldl_final_prev",
            "lineageTag": "dbdfa357-7550-4ad7-a05e-76b1ab879648",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_final_delta",
            "dataType": "double",
            "sourceColumn": "ldl_final_delta",
            "lineageTag": "6fa6990f-a4ea-4b89-96cf-56ed8a9288d4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_final_pct_change",
            "dataType": "double",
            "sourceColumn": "ldl_final_pct_change",
            "lineageTag": "e093261e-aad2-4f1e-8593-abc7d7679b0a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_final_rolling3",
            "dataType": "double",
            "sourceColumn": "ldl_final_rolling3",
            "lineageTag": "543c2f48-4999-4579-a04d-11ea326dd81c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "triglycerides_prev",
            "dataType": "double",
            "sourceColumn": "triglycerides_prev",
            "lineageTag": "955e751f-6447-41d6-b681-3d3f7e7b6ce4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "triglycerides_delta",
            "dataType": "double",
            "sourceColumn": "triglycerides_delta",
            "lineageTag": "82373363-7e8c-4959-b877-1f4466938394",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "triglycerides_pct_change",
            "dataType": "double",
            "sourceColumn": "triglycerides_pct_change",
            "lineageTag": "ff74e2a4-2722-47f7-aa47-dc496b81bfec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "triglycerides_rolling3",
            "dataType": "double",
            "sourceColumn": "triglycerides_rolling3",
            "lineageTag": "fa3f34bd-391b-4e95-9680-966fd22f3cd0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "non_hdl_final_prev",
            "dataType": "double",
            "sourceColumn": "non_hdl_final_prev",
            "lineageTag": "057bce8d-1fa9-49be-93a0-b6e8751c58c8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "non_hdl_final_delta",
            "dataType": "double",
            "sourceColumn": "non_hdl_final_delta",
            "lineageTag": "c2dc1924-3b91-4064-860d-4e28520193ff",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "non_hdl_final_pct_change",
            "dataType": "double",
            "sourceColumn": "non_hdl_final_pct_change",
            "lineageTag": "5f4a9689-a177-4979-b46d-9cee2bdf9dd2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "non_hdl_final_rolling3",
            "dataType": "double",
            "sourceColumn": "non_hdl_final_rolling3",
            "lineageTag": "378cb857-7bda-429e-a568-90bbd3a6b7ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tc_hdl_ratio_prev",
            "dataType": "double",
            "sourceColumn": "tc_hdl_ratio_prev",
            "lineageTag": "bd76e1ae-52e8-42c0-b79b-045ee5f5d6b8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tc_hdl_ratio_delta",
            "dataType": "double",
            "sourceColumn": "tc_hdl_ratio_delta",
            "lineageTag": "e4940e2c-70ee-4224-97c4-9456292cef47",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tc_hdl_ratio_pct_change",
            "dataType": "double",
            "sourceColumn": "tc_hdl_ratio_pct_change",
            "lineageTag": "7e7cd210-e348-4b94-b4f4-88ceba7d05c8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tc_hdl_ratio_rolling3",
            "dataType": "double",
            "sourceColumn": "tc_hdl_ratio_rolling3",
            "lineageTag": "54b94664-074d-4fe8-b391-99d4b951aa09",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_hdl_ratio_prev",
            "dataType": "double",
            "sourceColumn": "ldl_hdl_ratio_prev",
            "lineageTag": "14554719-458e-44f6-b928-dffd82544bee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_hdl_ratio_delta",
            "dataType": "double",
            "sourceColumn": "ldl_hdl_ratio_delta",
            "lineageTag": "adb88c72-3396-49e3-beae-213c017c0282",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_hdl_ratio_pct_change",
            "dataType": "double",
            "sourceColumn": "ldl_hdl_ratio_pct_change",
            "lineageTag": "8ad8e45a-5d0b-4cd4-9e5e-cb7a47a4d72a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldl_hdl_ratio_rolling3",
            "dataType": "double",
            "sourceColumn": "ldl_hdl_ratio_rolling3",
            "lineageTag": "5959369d-e4e7-434d-bd21-66d657e33e2a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tg_hdl_ratio_prev",
            "dataType": "double",
            "sourceColumn": "tg_hdl_ratio_prev",
            "lineageTag": "4c997038-3224-4300-b7cd-b9c5898946e3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tg_hdl_ratio_delta",
            "dataType": "double",
            "sourceColumn": "tg_hdl_ratio_delta",
            "lineageTag": "50fb9e04-d735-4df3-9de7-f5aaa6cd91e1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tg_hdl_ratio_pct_change",
            "dataType": "double",
            "sourceColumn": "tg_hdl_ratio_pct_change",
            "lineageTag": "29332c82-976b-4676-83f4-a9b3ba4f4c10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tg_hdl_ratio_rolling3",
            "dataType": "double",
            "sourceColumn": "tg_hdl_ratio_rolling3",
            "lineageTag": "73295747-7ff3-4a72-ae6a-020f6e59d785",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "aip_prev",
            "dataType": "double",
            "sourceColumn": "aip_prev",
            "lineageTag": "23742592-2800-4d28-8032-c478cce6ee1a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "aip_delta",
            "dataType": "double",
            "sourceColumn": "aip_delta",
            "lineageTag": "a43a4c33-3b27-4447-9c83-a3b146430339",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "aip_pct_change",
            "dataType": "double",
            "sourceColumn": "aip_pct_change",
            "lineageTag": "5d06588e-adc9-44dc-ae79-2e4e0504d7f5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "aip_rolling3",
            "dataType": "double",
            "sourceColumn": "aip_rolling3",
            "lineageTag": "639f23b7-715f-4612-bba4-1ce614987a55",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "remnant_cholesterol_prev",
            "dataType": "double",
            "sourceColumn": "remnant_cholesterol_prev",
            "lineageTag": "f0013c2a-3f27-48a4-8cad-6bf5b2c3f188",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "remnant_cholesterol_delta",
            "dataType": "double",
            "sourceColumn": "remnant_cholesterol_delta",
            "lineageTag": "1044e42c-4509-4cd8-bc5e-477b0242a4b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "remnant_cholesterol_pct_change",
            "dataType": "double",
            "sourceColumn": "remnant_cholesterol_pct_change",
            "lineageTag": "1b4904ca-94c3-42a6-b51e-34abb428dbf8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "remnant_cholesterol_rolling3",
            "dataType": "double",
            "sourceColumn": "remnant_cholesterol_rolling3",
            "lineageTag": "902b636c-c5f7-47c4-8063-ac65137f78c0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "lpa_prev",
            "dataType": "double",
            "sourceColumn": "lpa_prev",
            "lineageTag": "7b187781-0be4-4873-bd5c-18b168e38ecf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "lpa_delta",
            "dataType": "double",
            "sourceColumn": "lpa_delta",
            "lineageTag": "8491f78e-802b-42d1-b9e7-bd86c24de7bf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "lpa_pct_change",
            "dataType": "double",
            "sourceColumn": "lpa_pct_change",
            "lineageTag": "0161fdc5-1d5c-4bec-bc34-80e716531773",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "lpa_rolling3",
            "dataType": "double",
            "sourceColumn": "lpa_rolling3",
            "lineageTag": "945d5cc8-065e-46eb-8c0c-49a4a338fad0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "has_core_lipids",
            "dataType": "double",
            "sourceColumn": "has_core_lipids",
            "lineageTag": "50d70f57-01f0-498c-b1c6-9cfe43c6ecb4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "is_complete_profile",
            "dataType": "double",
            "sourceColumn": "is_complete_profile",
            "lineageTag": "bc5ec4e1-5b84-433a-841e-9813367ee132",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "record_quality_note",
            "dataType": "string",
            "sourceColumn": "record_quality_note",
            "lineageTag": "e2c8add3-ee53-4df3-8d2a-201db3df428b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "created_at",
            "dataType": "string",
            "sourceColumn": "created_at",
            "lineageTag": "4eba2b08-92e7-4555-bf4e-377f28e124ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "updated_at",
            "dataType": "string",
            "sourceColumn": "updated_at",
            "lineageTag": "855d7e84-2059-4377-a182-d234f493b9bb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_LipidMetrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"dsn=bllod_raw\", [HierarchicalNavigation=true]),",
                "    lipid_metrics_Table = Source{[Name=\"lipid_metrics\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(lipid_metrics_Table, {{\"exam_date\", type date}}, \"el-GR\")",
                "in",
                "    #\"Changed Type with Locale\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Lipid Latest Total Cholesterol",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[total_cholesterol]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest Total Cholesterol Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "e4ce3e4b-773f-48c3-95f4-731b60371a2b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Lipid Previous Total Cholesterol",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[total_cholesterol]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous Total Cholesterol Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "24b6fd96-4b54-4bf5-9e64-2adfff1e2e39"
          },
          {
            "name": "Lipid Total Cholesterol Delta",
            "expression": "[Lipid Latest Total Cholesterol] - [Lipid Previous Total Cholesterol]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "75f85642-564c-4bc9-8c33-e56718f480a9"
          },
          {
            "name": "Lipid Total Cholesterol Delta %",
            "expression": "DIVIDE([Lipid Total Cholesterol Delta], [Lipid Previous Total Cholesterol])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "73055aed-ef88-4f4a-b725-e982f9ff5fc8"
          },
          {
            "name": "Lipid Total Cholesterol Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[total_cholesterol])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[total_cholesterol]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "94594593-2383-48cf-8cdc-ef7f0208e158"
          },
          {
            "name": "Lipid Latest HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[hdl]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "4b94bd79-a117-4f3a-b15c-b64fb2493c98"
          },
          {
            "name": "Lipid Previous HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[hdl]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "10ce3a65-1940-4183-bc4a-e748ab3f3938"
          },
          {
            "name": "Lipid HDL Delta",
            "expression": "[Lipid Latest HDL] - [Lipid Previous HDL]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "86d73463-27ea-461d-81d5-99a4c3baff82"
          },
          {
            "name": "Lipid HDL Delta %",
            "expression": "DIVIDE([Lipid HDL Delta], [Lipid Previous HDL])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "9800f678-e9af-430d-a5a7-adb1cf5f0c48"
          },
          {
            "name": "Lipid HDL Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[hdl])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[hdl]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "7349b4f6-92c3-428b-8bec-5279f5caaff9"
          },
          {
            "name": "Lipid Latest LDL Final",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[ldl_final]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest LDL Final Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "952a5648-c8a6-41c3-b41a-a5c9850a153c"
          },
          {
            "name": "Lipid Previous LDL Final",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[ldl_final]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous LDL Final Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "7a9c8890-7225-4f0b-bc70-f4b3bf3669f6"
          },
          {
            "name": "Lipid LDL Final Delta",
            "expression": "[Lipid Latest LDL Final] - [Lipid Previous LDL Final]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "3b31cdf0-f19b-435a-aed4-7d8f1e693908"
          },
          {
            "name": "Lipid LDL Final Delta %",
            "expression": "DIVIDE([Lipid LDL Final Delta], [Lipid Previous LDL Final])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "00e4ce77-b641-4e53-9c22-281377ec2cd5"
          },
          {
            "name": "Lipid LDL Final Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[ldl_final])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[ldl_final]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "e294ffa8-9a72-450c-9f1b-100ac68b8795"
          },
          {
            "name": "Lipid Latest TG",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[triglycerides]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest TG Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "4317a5d9-11dc-42ae-a9e9-f3e5a7db6fe1"
          },
          {
            "name": "Lipid Previous TG",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[triglycerides]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous TG Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "c5744887-50f4-4e03-8176-7d4f900cf38b"
          },
          {
            "name": "Lipid TG Delta",
            "expression": "[Lipid Latest TG] - [Lipid Previous TG]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "006a4055-d258-411c-b02a-f61afde7a867"
          },
          {
            "name": "Lipid TG Delta %",
            "expression": "DIVIDE([Lipid TG Delta], [Lipid Previous TG])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "b97eff3a-4227-4c1e-9588-f2ea3b4e88dd"
          },
          {
            "name": "Lipid TG Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[triglycerides])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[triglycerides]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "05f18913-7f4c-4b82-94d4-6ce848274a7a"
          },
          {
            "name": "Lipid Latest Non-HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[non_hdl_final]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest Non-HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "5ea13db3-ecf7-43e7-a1f3-55cf114fe7ae"
          },
          {
            "name": "Lipid Previous Non-HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[non_hdl_final]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous Non-HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "e9309f9d-ece3-410a-84a5-ff81bf658d43"
          },
          {
            "name": "Lipid Non-HDL Delta",
            "expression": "[Lipid Latest Non-HDL] - [Lipid Previous Non-HDL]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "bcd0bc27-d1a5-401e-bdfb-346fa4c7f0c1"
          },
          {
            "name": "Lipid Non-HDL Delta %",
            "expression": "DIVIDE([Lipid Non-HDL Delta], [Lipid Previous Non-HDL])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "4ace2f3b-1f70-409d-84db-420738dffecc"
          },
          {
            "name": "Lipid Non-HDL Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[non_hdl_final])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[non_hdl_final]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "9110eef8-a598-4396-96cd-147e39b14659"
          },
          {
            "name": "Lipid Latest TC/HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[tc_hdl_ratio]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest TC/HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "ad19d525-5c19-4cc9-97ab-1cfe09a245cb"
          },
          {
            "name": "Lipid Previous TC/HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[tc_hdl_ratio]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous TC/HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "c61cb6b4-51eb-44dd-bff8-5040fa7d7173"
          },
          {
            "name": "Lipid TC/HDL Delta",
            "expression": "[Lipid Latest TC/HDL] - [Lipid Previous TC/HDL]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "1b9dad27-8d47-43fc-b1f6-3444bbe72cf2"
          },
          {
            "name": "Lipid TC/HDL Delta %",
            "expression": "DIVIDE([Lipid TC/HDL Delta], [Lipid Previous TC/HDL])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "57af3431-a6db-49a6-b2ec-526bb0f1051b"
          },
          {
            "name": "Lipid TC/HDL Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[tc_hdl_ratio])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[tc_hdl_ratio]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "9266905a-569b-4cf0-85c2-92e449994864"
          },
          {
            "name": "Lipid Latest LDL/HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[ldl_hdl_ratio]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest LDL/HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "11389937-ddd3-447f-85be-704ead7fcc90"
          },
          {
            "name": "Lipid Previous LDL/HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[ldl_hdl_ratio]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous LDL/HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "42228e85-d600-4ada-8064-8695f0c3027f"
          },
          {
            "name": "Lipid LDL/HDL Delta",
            "expression": "[Lipid Latest LDL/HDL] - [Lipid Previous LDL/HDL]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "7c4b2013-69fc-49f1-bcac-774f4823cca2"
          },
          {
            "name": "Lipid LDL/HDL Delta %",
            "expression": "DIVIDE([Lipid LDL/HDL Delta], [Lipid Previous LDL/HDL])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "f2defeaa-f79d-4fe4-bae5-c598a6e227f2"
          },
          {
            "name": "Lipid LDL/HDL Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[ldl_hdl_ratio])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[ldl_hdl_ratio]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "0befae3a-462a-4ed9-b901-8d0fd8d3b632"
          },
          {
            "name": "Lipid Latest TG/HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[tg_hdl_ratio]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest TG/HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "46a2d34e-b418-40e2-93bc-14be982f3070"
          },
          {
            "name": "Lipid Previous TG/HDL",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[tg_hdl_ratio]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous TG/HDL Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "4676f582-a6d5-44b6-987f-dfd893a320a6"
          },
          {
            "name": "Lipid TG/HDL Delta",
            "expression": "[Lipid Latest TG/HDL] - [Lipid Previous TG/HDL]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "6615b91c-e2d0-4a27-8191-122b0a8d4f92"
          },
          {
            "name": "Lipid TG/HDL Delta %",
            "expression": "DIVIDE([Lipid TG/HDL Delta], [Lipid Previous TG/HDL])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "f7588ab9-fe5c-49e4-a8df-fffc11800520"
          },
          {
            "name": "Lipid TG/HDL Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[tg_hdl_ratio])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[tg_hdl_ratio]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "29d5544f-aad0-448a-bf32-45f217faf485"
          },
          {
            "name": "Lipid Latest AIP",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[aip]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest AIP Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "9a4a6bf5-442e-4670-b521-c3fbdb2b5740"
          },
          {
            "name": "Lipid Previous AIP",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[aip]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous AIP Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "50f560a3-b392-4505-92bb-e6721a0423f1"
          },
          {
            "name": "Lipid AIP Delta",
            "expression": "[Lipid Latest AIP] - [Lipid Previous AIP]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "aa2efdf1-dfdb-47e6-893e-ed2b70c5d08a"
          },
          {
            "name": "Lipid AIP Delta %",
            "expression": "DIVIDE([Lipid AIP Delta], [Lipid Previous AIP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "ee59a18e-479d-402a-9261-672632c4aa3a"
          },
          {
            "name": "Lipid AIP Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[aip])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[aip]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "6672c31b-9851-43ff-88d1-f074cebfb57d"
          },
          {
            "name": "Lipid Latest Remnant",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[remnant_cholesterol]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest Remnant Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "57952208-6c6a-43fd-8098-30dff7ada2f8"
          },
          {
            "name": "Lipid Previous Remnant",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[remnant_cholesterol]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous Remnant Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "300af85d-849f-4ec9-ace2-14c7f6a41711"
          },
          {
            "name": "Lipid Remnant Delta",
            "expression": "[Lipid Latest Remnant] - [Lipid Previous Remnant]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "1746be9c-6d9f-4ca9-9a39-d01512ef32e0"
          },
          {
            "name": "Lipid Remnant Delta %",
            "expression": "DIVIDE([Lipid Remnant Delta], [Lipid Previous Remnant])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "6337ab00-9363-4dea-8eab-f0f804dec9ee"
          },
          {
            "name": "Lipid Remnant Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[remnant_cholesterol])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[remnant_cholesterol]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "2174ae50-ff07-468d-a51f-5a6f48dde72d"
          },
          {
            "name": "Lipid Latest Lp(a)",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[lpa]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Latest Lp(a) Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Latest",
            "lineageTag": "70476baf-6a1f-4ba9-96b4-9331e8913131"
          },
          {
            "name": "Lipid Previous Lp(a)",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(Fact_LipidMetrics[lpa]),",
              "    FILTER(",
              "        ALL(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] = [Lipid Previous Lp(a) Data Date]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Previous",
            "lineageTag": "456cbfa2-8a74-402b-a6f6-55b21f9d5266"
          },
          {
            "name": "Lipid Lp(a) Delta",
            "expression": "[Lipid Latest Lp(a)] - [Lipid Previous Lp(a)]",
            "formatString": "0.00",
            "displayFolder": "Lipid - Delta",
            "lineageTag": "300fb929-c144-4624-99f7-33fbf9f30483"
          },
          {
            "name": "Lipid Lp(a) Delta %",
            "expression": "DIVIDE([Lipid Lp(a) Delta], [Lipid Previous Lp(a)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Lipid - Delta %",
            "lineageTag": "5f61403a-3ad0-44f3-8717-cd555df92c3d"
          },
          {
            "name": "Lipid Lp(a) Rolling 3",
            "expression": [
              "",
              "AVERAGEX(",
              "    TOPN(",
              "        3,",
              "        FILTER(",
              "            ALLSELECTED(Fact_LipidMetrics),",
              "            NOT ISBLANK(Fact_LipidMetrics[lpa])",
              "        ),",
              "        Fact_LipidMetrics[exam_date], DESC",
              "    ),",
              "    CALCULATE(MAX(Fact_LipidMetrics[lpa]))",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - Rolling 3",
            "lineageTag": "9cef7293-d377-4e0b-9427-54ae28a7c507"
          },
          {
            "name": "Lipid Total Cholesterol Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid Total Cholesterol Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "5c85ffc4-2753-401e-ad7e-105f0e51c9fa"
          },
          {
            "name": "Lipid HDL Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid HDL Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d > 0, \"Improving\",",
              "    d < 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "e2e6e590-0aa7-4042-8380-593148a014b4"
          },
          {
            "name": "Lipid LDL Final Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid LDL Final Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "ec361f11-2530-4719-b141-fafaa1cff86a"
          },
          {
            "name": "Lipid TG Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid TG Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "4d901068-42be-4081-80e6-de86f1080827"
          },
          {
            "name": "Lipid Non-HDL Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid Non-HDL Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "1a8fb48e-dcfd-4353-a66c-348cbb3dbde6"
          },
          {
            "name": "Lipid TC/HDL Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid TC/HDL Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "f9563039-f798-4838-8eeb-95c5f0a4b26c"
          },
          {
            "name": "Lipid LDL/HDL Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid LDL/HDL Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "e080af07-33ce-42da-baf3-8abd1f77bd45"
          },
          {
            "name": "Lipid TG/HDL Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid TG/HDL Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "086b1025-e921-40e0-ac55-58efeccbec48"
          },
          {
            "name": "Lipid AIP Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid AIP Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "cc0ed87b-81cd-444d-b5fc-1750bcd9e07c"
          },
          {
            "name": "Lipid Remnant Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid Remnant Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "96b97edf-8406-42ec-9754-a393f001d200"
          },
          {
            "name": "Lipid Lp(a) Trend Direction",
            "expression": [
              "",
              "VAR d = [Lipid Lp(a) Delta]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(d), BLANK(),",
              "    d < 0, \"Improving\",",
              "    d > 0, \"Worsening\",",
              "    \"Stable\"",
              ")"
            ],
            "displayFolder": "Lipid - Trend",
            "lineageTag": "fd4dd491-b3fb-49b1-aa56-72b2138c22a9"
          },
          {
            "name": "Lipid AIP Score",
            "expression": [
              "",
              "VAR x = [Lipid Latest AIP]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 0.11, 1,",
              "    x < 0.21, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "f68b0831-e868-4836-ae78-b5ba9f251083"
          },
          {
            "name": "Lipid TG/HDL Score",
            "expression": [
              "",
              "VAR x = [Lipid Latest TG/HDL]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 2, 1,",
              "    x < 3, 2,",
              "    x < 4, 3,",
              "    4",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "1723da84-9383-4668-b078-ec6efd709883"
          },
          {
            "name": "Lipid Remnant Score",
            "expression": [
              "",
              "VAR x = [Lipid Latest Remnant]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 20, 1,",
              "    x <= 30, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "ab740bd6-7505-44ad-aa39-1049e6b7e0f0"
          },
          {
            "name": "Lipid TC/HDL Score",
            "expression": [
              "",
              "VAR x = [Lipid Latest TC/HDL]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 4, 1,",
              "    x < 5, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "0c23f692-b5de-4790-91fc-7ff778998e13"
          },
          {
            "name": "Lipid LDL/HDL Score",
            "expression": [
              "",
              "VAR x = [Lipid Latest LDL/HDL]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 2, 1,",
              "    x < 3, 2,",
              "    3",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "8ff34f63-b03f-4f64-a28f-752a388eb320"
          },
          {
            "name": "Lipid Non-HDL Score",
            "expression": [
              "",
              "VAR x = [Lipid Latest Non-HDL]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x < 130, 1,",
              "    x < 160, 2,",
              "    x < 190, 3,",
              "    4",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "29c16178-50fd-4d5d-a735-1b360dd4e9e5"
          },
          {
            "name": "Lipid AIP Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid AIP Score],",
              "    1, \"Low risk\",",
              "    2, \"Intermediate risk\",",
              "    3, \"High risk\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "1b135e4a-239f-44b6-9f70-679ad13b52f8"
          },
          {
            "name": "Lipid TG/HDL Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid TG/HDL Score],",
              "    1, \"Favorable\",",
              "    2, \"Borderline\",",
              "    3, \"Higher risk\",",
              "    4, \"Marked metabolic-risk signal\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "2d9348e1-1595-408e-9e91-04db3efb1022"
          },
          {
            "name": "Lipid Remnant Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid Remnant Score],",
              "    1, \"Favorable\",",
              "    2, \"Borderline\",",
              "    3, \"Higher residual risk\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "3b89b128-58ff-4a71-8ab6-855ab50e2a4e"
          },
          {
            "name": "Lipid TC/HDL Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid TC/HDL Score],",
              "    1, \"Favorable\",",
              "    2, \"Borderline\",",
              "    3, \"Higher risk\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "9289f748-9a5b-49d6-89c7-537828c787eb"
          },
          {
            "name": "Lipid LDL/HDL Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid LDL/HDL Score],",
              "    1, \"Favorable\",",
              "    2, \"Borderline\",",
              "    3, \"Less favorable\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "07c4283d-9a50-4cc7-9ac7-171d1c1e5234"
          },
          {
            "name": "Lipid Non-HDL Indicator",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid Non-HDL Score],",
              "    1, \"Optimal / near-optimal\",",
              "    2, \"Borderline high\",",
              "    3, \"High\",",
              "    4, \"Very high\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "60bae0c0-5ad4-4579-abaf-866327222db3"
          },
          {
            "name": "Lipid Composite Risk Score",
            "expression": [
              "",
              "AVERAGEX(",
              "    {",
              "        [Lipid AIP Score],",
              "        [Lipid TG/HDL Score],",
              "        [Lipid Remnant Score],",
              "        [Lipid TC/HDL Score],",
              "        [Lipid LDL/HDL Score],",
              "        [Lipid Non-HDL Score]",
              "    },",
              "    [Value]",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Lipid - KPI",
            "lineageTag": "c07473a8-a0ef-4f2c-840f-e5ae5b655b85"
          },
          {
            "name": "Lipid Composite KPI",
            "expression": [
              "",
              "VAR x = [Lipid Composite Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.5, \"Favorable\",",
              "    x <= 2.3, \"Monitor\",",
              "    x <= 3.2, \"Elevated risk pattern\",",
              "    \"High concern\"",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "6e6c2383-9acf-4e7a-aa90-d465b2d857af"
          },
          {
            "name": "Lipid Composite Color Hex",
            "expression": [
              "",
              "VAR x = [Lipid Composite Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.5, \"#2E7D32\",",
              "    x <= 2.3, \"#F9A825\",",
              "    x <= 3.2, \"#EF6C00\",",
              "    \"#C62828\"",
              ")"
            ],
            "displayFolder": "Lipid - KPI",
            "lineageTag": "6419d76c-6d64-4c31-a2de-45f71de80201"
          },
          {
            "name": "Lipid AIP Stability KPI",
            "expression": "ABS([Lipid Latest AIP] - [Lipid AIP Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Lipid - Stability",
            "lineageTag": "72f7997e-c6d8-4fda-bf5b-342a0691c5f6"
          },
          {
            "name": "Lipid TG/HDL Stability KPI",
            "expression": "ABS([Lipid Latest TG/HDL] - [Lipid TG/HDL Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Lipid - Stability",
            "lineageTag": "802fc3e0-4af4-4c14-80b2-b6d598723193"
          },
          {
            "name": "Lipid Remnant Stability KPI",
            "expression": "ABS([Lipid Latest Remnant] - [Lipid Remnant Rolling 3])",
            "formatString": "0.00",
            "displayFolder": "Lipid - Stability",
            "lineageTag": "5a444870-62a1-4600-906c-340eba3df71b"
          },
          {
            "name": "Combined Metabolic Risk Score",
            "expression": [
              "",
              "AVERAGEX(",
              "    {",
              "        [Lipid AIP Score],",
              "        [Lipid TG/HDL Score],",
              "        [Lipid Remnant Score],",
              "        [Endo HOMA-IR Score],",
              "        [Endo QUICKI Score],",
              "        [Endo HbA1c Score],",
              "        [Endo Glucose Score]",
              "    },",
              "    [Value]",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Combined - KPI",
            "lineageTag": "1a291852-db21-4797-a7b9-5b993f6f0f29"
          },
          {
            "name": "Combined Metabolic KPI",
            "expression": [
              "",
              "VAR x = [Combined Metabolic Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.5, \"Favorable\",",
              "    x <= 2.2, \"Monitor\",",
              "    x <= 3.0, \"Elevated combined metabolic risk\",",
              "    \"High combined metabolic risk\"",
              ")"
            ],
            "displayFolder": "Combined - KPI",
            "lineageTag": "7afc1e9f-f5ff-4b5d-bcae-f2a9220690fd"
          },
          {
            "name": "Combined Metabolic Color Hex",
            "expression": [
              "",
              "VAR x = [Combined Metabolic Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.5, \"#2E7D32\",",
              "    x <= 2.2, \"#F9A825\",",
              "    x <= 3.0, \"#EF6C00\",",
              "    \"#C62828\"",
              ")"
            ],
            "displayFolder": "Combined - KPI",
            "lineageTag": "ca102f40-fa6a-4f9f-b860-1ad1ccf62b6d"
          },
          {
            "name": "Color - Good",
            "expression": "\"#2E7D32\"",
            "displayFolder": "Formatting - Colors",
            "lineageTag": "b719bfb2-2763-4826-beae-a52f22d6f0ac"
          },
          {
            "name": "Color - Warning",
            "expression": "\"#F9A825\"",
            "displayFolder": "Formatting - Colors",
            "lineageTag": "16607e55-1a70-4874-890f-48aad7886ba4"
          },
          {
            "name": "Color - Elevated",
            "expression": "\"#EF6C00\"",
            "displayFolder": "Formatting - Colors",
            "lineageTag": "766f9676-d721-4955-a77d-adb7c60b971c"
          },
          {
            "name": "Color - Bad",
            "expression": "\"#C62828\"",
            "displayFolder": "Formatting - Colors",
            "lineageTag": "7568a479-1c58-4df9-8d7c-5e68c1df14dc"
          },
          {
            "name": "Lipid AIP Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid AIP Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "9e6741f1-835e-4884-b47d-6a8b0b50aafe"
          },
          {
            "name": "Lipid TG/HDL Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid TG/HDL Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#EF6C00\",",
              "    4, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "508c1bcf-547f-47cd-9819-ebaf1154abff"
          },
          {
            "name": "Lipid Remnant Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid Remnant Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "da308360-ffed-48ce-8f30-15e13ede5a30"
          },
          {
            "name": "Lipid TC/HDL Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid TC/HDL Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "c91e8287-32d5-4a0d-b26e-1f60e240a8d6"
          },
          {
            "name": "Lipid LDL/HDL Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid LDL/HDL Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "652c55d9-08ba-44c0-a74e-3735caaa48b0"
          },
          {
            "name": "Lipid Non-HDL Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid Non-HDL Score],",
              "    1, \"#2E7D32\",",
              "    2, \"#F9A825\",",
              "    3, \"#EF6C00\",",
              "    4, \"#C62828\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "b182e925-1d65-4bac-a181-f9319b65ea65"
          },
          {
            "name": "Lipid Composite Background Hex",
            "expression": "[Lipid Composite Color Hex]",
            "displayFolder": "Formatting - Lipid",
            "lineageTag": "67a76458-c6bf-4c8c-80fd-addbf6bf6e08"
          },
          {
            "name": "Lipid AIP Trend Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid AIP Trend Direction],",
              "    \"Improving\", \"#2E7D32\",",
              "    \"Worsening\", \"#C62828\",",
              "    \"Stable\", \"#9E9E9E\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Trend",
            "lineageTag": "c5d9b683-c6a6-4036-8fff-c89d951fd5e9"
          },
          {
            "name": "Lipid TG/HDL Trend Color Hex",
            "expression": [
              "",
              "SWITCH(",
              "    [Lipid TG/HDL Trend Direction],",
              "    \"Improving\", \"#2E7D32\",",
              "    \"Worsening\", \"#C62828\",",
              "    \"Stable\", \"#9E9E9E\",",
              "    BLANK()",
              ")"
            ],
            "displayFolder": "Formatting - Trend",
            "lineageTag": "32d7f349-fd02-4cf9-9d5a-614cf4ae80e6"
          },
          {
            "name": "Combined KPI Background Hex",
            "expression": "[Combined Metabolic Color Hex]",
            "displayFolder": "Formatting - Combined",
            "lineageTag": "ed7cd82a-0a70-4565-b942-077b02c66922"
          },
          {
            "name": "Combined KPI Status Color Hex",
            "expression": [
              "",
              "VAR x = [Combined Metabolic Risk Score]",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK(x), BLANK(),",
              "    x <= 1.5, \"#2E7D32\",",
              "    x <= 2.2, \"#F9A825\",",
              "    x <= 3.0, \"#EF6C00\",",
              "    \"#C62828\"",
              ")"
            ],
            "displayFolder": "Formatting - Combined",
            "lineageTag": "c1cb6632-8546-4a82-94cf-1f5e393edd46"
          },
          {
            "name": "Lipid Days Since Previous Test",
            "expression": [
              "",
              "DATEDIFF([Previous Selected Date], [Latest Selected Date], DAY)"
            ],
            "displayFolder": "Lipid - Previous",
            "lineageTag": "9d74d26a-50a8-4cac-aa96-c93413f27420",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Lipid Latest Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[total_cholesterol])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "displayFolder": "Lipid - Latest",
            "lineageTag": "55ed9e2b-2375-4fdb-83cf-2be75e30f442",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Lipid Previous Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[total_cholesterol])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "displayFolder": "Lipid - Previous",
            "lineageTag": "f28b0f7e-2b09-4079-85a6-13e9de844752",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Lipid Latest Total Cholesterol Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[total_cholesterol])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "e3e65247-34f2-488f-b3d9-dd6d48c5ddb4"
          },
          {
            "name": "Lipid Previous Total Cholesterol Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest Total Cholesterol Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[total_cholesterol])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "e502bcc7-adcc-428c-9a74-27f652f76e35"
          },
          {
            "name": "Lipid Latest HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[hdl])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "105b4c34-fe5d-4007-a9df-657293f43758"
          },
          {
            "name": "Lipid Previous HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest HDL Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[hdl])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "459212e7-f04e-43a7-8976-44a5bb74916e"
          },
          {
            "name": "Lipid Latest LDL Final Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[ldl_final])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "6a77769c-eb44-4f09-8c36-324beec75b50"
          },
          {
            "name": "Lipid Previous LDL Final Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest LDL Final Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[ldl_final])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "69f5275e-2332-443d-a2e7-0e4a37c5fdac"
          },
          {
            "name": "Lipid Latest TG Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[triglycerides])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "2ac967cb-02ef-4984-b735-25cb2c0d2d2c"
          },
          {
            "name": "Lipid Previous TG Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest TG Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[triglycerides])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "ef948918-b9d8-493d-83e5-3ea682cf8108"
          },
          {
            "name": "Lipid Latest Non-HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[non_hdl_final])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "33ed0347-4f2b-4daf-a9dd-1184ecf5ff20"
          },
          {
            "name": "Lipid Previous Non-HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest Non-HDL Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[non_hdl_final])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "34de2687-5c04-4135-bb4d-a3436c64a04a"
          },
          {
            "name": "Lipid Latest TC/HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[tc_hdl_ratio])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "d22a0376-7189-40d1-89da-efbde13f2cee"
          },
          {
            "name": "Lipid Previous TC/HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest TC/HDL Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[tc_hdl_ratio])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "5639a1b6-7d1a-4326-b60a-7f4a63adae65"
          },
          {
            "name": "Lipid Latest LDL/HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[ldl_hdl_ratio])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "3d977bc1-e5a2-4cba-a7bc-c55b7e8aa302"
          },
          {
            "name": "Lipid Previous LDL/HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest LDL/HDL Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[ldl_hdl_ratio])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "32aed538-769e-4ac8-ac81-54562b08fff1"
          },
          {
            "name": "Lipid Latest TG/HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[tg_hdl_ratio])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "07894cf0-f9ec-48d3-bf14-ea37df210a83"
          },
          {
            "name": "Lipid Previous TG/HDL Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest TG/HDL Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[tg_hdl_ratio])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "553ae863-0d8b-48ac-bde2-2f8db578ace5"
          },
          {
            "name": "Lipid Latest AIP Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[aip])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "3f68d061-54d5-4ad8-a9ce-65086dea7489"
          },
          {
            "name": "Lipid Previous AIP Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest AIP Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[aip])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "d685e3aa-b8ba-4cce-90ca-4a5432eb6f74"
          },
          {
            "name": "Lipid Latest Remnant Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[remnant_cholesterol])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "42f0741f-c280-4869-b1f4-4279a82d727f"
          },
          {
            "name": "Lipid Previous Remnant Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest Remnant Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[remnant_cholesterol])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "2ef9943f-2735-487f-9db2-c2e5250e6bb4"
          },
          {
            "name": "Lipid Latest Lp(a) Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        NOT ISBLANK(Fact_LipidMetrics[lpa])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "97b6f31d-aa5e-4e0e-99a0-cb18e44a2d92"
          },
          {
            "name": "Lipid Previous Lp(a) Data Date",
            "expression": [
              "",
              "MAXX(",
              "    FILTER(",
              "        ALLSELECTED(Fact_LipidMetrics),",
              "        Fact_LipidMetrics[exam_date] < [Lipid Latest Lp(a) Data Date]",
              "            && NOT ISBLANK(Fact_LipidMetrics[lpa])",
              "    ),",
              "    Fact_LipidMetrics[exam_date]",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "50cc4822-80af-48ed-a0c3-fcaa259fc369"
          },
          {
            "name": "Lipid Days Between Latest And Previous Test",
            "expression": "DATEDIFF([Lipid Previous Total Cholesterol Data Date], [Lipid Latest Total Cholesterol Data Date], DAY)",
            "formatString": "0",
            "displayFolder": "Lipid - Data Dates",
            "lineageTag": "28068781-ff4a-4558-90e5-0aa691288093"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Fact_LiverMetrics",
        "lineageTag": "a741aadb-c537-4a38-88ba-ec7d8611132a",
        "columns": [
          {
            "name": "exam_date",
            "dataType": "dateTime",
            "sourceColumn": "exam_date",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "66ee601f-485e-4488-9651-680135314684",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "ast",
            "dataType": "double",
            "sourceColumn": "ast",
            "lineageTag": "ea4e2541-ef0c-42ca-b662-a7eb841f81b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alt",
            "dataType": "double",
            "sourceColumn": "alt",
            "lineageTag": "f663887a-7e5a-4456-a519-6781c4efc9b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ggt",
            "dataType": "double",
            "sourceColumn": "ggt",
            "lineageTag": "2dd4fd58-0c4b-4235-a307-55a8c7bc7722",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alp",
            "dataType": "double",
            "sourceColumn": "alp",
            "lineageTag": "311c8643-5b61-40b2-b632-899497a226b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_bilirubin",
            "dataType": "double",
            "sourceColumn": "total_bilirubin",
            "lineageTag": "96d83090-480a-45c6-a8b3-0d3b6b197b3f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_bilirubin",
            "dataType": "double",
            "sourceColumn": "direct_bilirubin",
            "lineageTag": "ecc2e4df-277d-41b9-86e7-733974e887cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "albumin",
            "dataType": "double",
            "sourceColumn": "albumin",
            "lineageTag": "ef8dc0aa-8144-499c-b803-9da28ce1ce1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldh",
            "dataType": "double",
            "sourceColumn": "ldh",
            "lineageTag": "92bd0006-7cea-439f-9f32-afe40c35fd51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_alt_ratio",
            "dataType": "double",
            "sourceColumn": "ast_alt_ratio",
            "lineageTag": "09bb5b3f-f1ca-4ec5-80a9-d232460c24ab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "indirect_bilirubin",
            "dataType": "double",
            "sourceColumn": "indirect_bilirubin",
            "lineageTag": "f24c8021-edfe-49d2-b17b-15e5846636cf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_total_bilirubin_pct",
            "dataType": "double",
            "sourceColumn": "direct_total_bilirubin_pct",
            "lineageTag": "32ad92b8-8c99-4983-8fc1-4ecc98b63b4d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_alt_pattern",
            "dataType": "string",
            "sourceColumn": "ast_alt_pattern",
            "lineageTag": "5a856c90-cec6-4758-bf12-49aa67ada2f9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "direct_total_bilirubin_risk",
            "dataType": "string",
            "sourceColumn": "direct_total_bilirubin_risk",
            "lineageTag": "c88fdff9-88fc-4f50-8356-5a49e60071db",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "bilirubin_pattern",
            "dataType": "string",
            "sourceColumn": "bilirubin_pattern",
            "lineageTag": "b679e43a-d59b-4e30-a4ad-359b0a457b3b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "ast_prev",
            "dataType": "double",
            "sourceColumn": "ast_prev",
            "lineageTag": "835456f6-a9ae-487b-a814-21a66c26e33e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_delta",
            "dataType": "double",
            "sourceColumn": "ast_delta",
            "lineageTag": "09be8b9a-f2fa-48e2-8992-168d35785f1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_pct_change",
            "dataType": "double",
            "sourceColumn": "ast_pct_change",
            "lineageTag": "396cc381-8a9e-4257-8026-2f91196f1d7a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_rolling3",
            "dataType": "double",
            "sourceColumn": "ast_rolling3",
            "lineageTag": "00460740-15aa-4936-81ea-50b6372fc985",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alt_prev",
            "dataType": "double",
            "sourceColumn": "alt_prev",
            "lineageTag": "925d3987-dd48-48f2-a2fc-f170d23cfb3c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alt_delta",
            "dataType": "double",
            "sourceColumn": "alt_delta",
            "lineageTag": "22b26094-f884-4384-81b0-dd5837d244e1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alt_pct_change",
            "dataType": "double",
            "sourceColumn": "alt_pct_change",
            "lineageTag": "c81feca2-1330-40e9-b74d-10d173348c50",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alt_rolling3",
            "dataType": "double",
            "sourceColumn": "alt_rolling3",
            "lineageTag": "a97a7c95-1e0c-4a78-8589-6456ca5accda",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ggt_prev",
            "dataType": "double",
            "sourceColumn": "ggt_prev",
            "lineageTag": "fe530c9f-1a93-48eb-937d-8e51614e7c5d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ggt_delta",
            "dataType": "double",
            "sourceColumn": "ggt_delta",
            "lineageTag": "020e9b50-0e76-46ba-8d98-4c3a24eedd7d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ggt_pct_change",
            "dataType": "double",
            "sourceColumn": "ggt_pct_change",
            "lineageTag": "027e43e0-0ad0-4671-8801-1160eb8c3ca4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ggt_rolling3",
            "dataType": "double",
            "sourceColumn": "ggt_rolling3",
            "lineageTag": "813634ca-39b9-4208-9d93-e7b45f0f071f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alp_prev",
            "dataType": "double",
            "sourceColumn": "alp_prev",
            "lineageTag": "76efc8d7-a18b-4074-8b9c-9eccbee15918",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alp_delta",
            "dataType": "double",
            "sourceColumn": "alp_delta",
            "lineageTag": "565021f3-966d-4216-852e-16768a6c61c6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alp_pct_change",
            "dataType": "double",
            "sourceColumn": "alp_pct_change",
            "lineageTag": "0c6fba40-3936-423c-9ba9-3d9bc01bf46d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "alp_rolling3",
            "dataType": "double",
            "sourceColumn": "alp_rolling3",
            "lineageTag": "d561fd8f-f5fd-41ab-9537-f99580b7620d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_bilirubin_prev",
            "dataType": "double",
            "sourceColumn": "total_bilirubin_prev",
            "lineageTag": "c6b2ee6d-644f-4f58-813f-c188e52c0e14",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_bilirubin_delta",
            "dataType": "double",
            "sourceColumn": "total_bilirubin_delta",
            "lineageTag": "4bc37cb5-1072-4773-9b24-84d0a31a11b5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_bilirubin_pct_change",
            "dataType": "double",
            "sourceColumn": "total_bilirubin_pct_change",
            "lineageTag": "1592f869-90b9-45c0-87b3-4845dc2c7e66",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "total_bilirubin_rolling3",
            "dataType": "double",
            "sourceColumn": "total_bilirubin_rolling3",
            "lineageTag": "20d5143f-78e7-40e7-9c4c-0c240535d1f7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_bilirubin_prev",
            "dataType": "double",
            "sourceColumn": "direct_bilirubin_prev",
            "lineageTag": "52e16b07-216b-4e79-9a0f-352cecba0c47",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_bilirubin_delta",
            "dataType": "double",
            "sourceColumn": "direct_bilirubin_delta",
            "lineageTag": "0e6f5bf4-29cd-41cd-8945-75b48c08f9bf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_bilirubin_pct_change",
            "dataType": "double",
            "sourceColumn": "direct_bilirubin_pct_change",
            "lineageTag": "f285afd1-324f-421e-b9ec-6d5634352071",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_bilirubin_rolling3",
            "dataType": "double",
            "sourceColumn": "direct_bilirubin_rolling3",
            "lineageTag": "e2d20ba7-4c1a-40ce-9bdb-442f069cfd1f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "albumin_prev",
            "dataType": "double",
            "sourceColumn": "albumin_prev",
            "lineageTag": "370170ac-b508-4cc8-9c27-bc00c58ca164",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "albumin_delta",
            "dataType": "double",
            "sourceColumn": "albumin_delta",
            "lineageTag": "736c56d8-f5f9-4772-8887-19118d678f19",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "albumin_pct_change",
            "dataType": "double",
            "sourceColumn": "albumin_pct_change",
            "lineageTag": "3216c7c1-cdef-4908-9589-93069137051a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "albumin_rolling3",
            "dataType": "double",
            "sourceColumn": "albumin_rolling3",
            "lineageTag": "45083557-b790-45f3-bb92-85ecfe9d6190",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldh_prev",
            "dataType": "double",
            "sourceColumn": "ldh_prev",
            "lineageTag": "902c246f-f36d-4be6-9acb-e06615667e38",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldh_delta",
            "dataType": "double",
            "sourceColumn": "ldh_delta",
            "lineageTag": "c83d3f89-23de-4093-9b95-b9d9c7f2ff7d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldh_pct_change",
            "dataType": "double",
            "sourceColumn": "ldh_pct_change",
            "lineageTag": "5426c802-5184-40b3-bb44-035fb4d9bf91",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ldh_rolling3",
            "dataType": "double",
            "sourceColumn": "ldh_rolling3",
            "lineageTag": "aaeb35a4-8976-44bd-8349-31d69aa1b7fe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_alt_ratio_prev",
            "dataType": "double",
            "sourceColumn": "ast_alt_ratio_prev",
            "lineageTag": "d382dd7d-f001-45ab-b963-ad69aa75cedd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_alt_ratio_delta",
            "dataType": "double",
            "sourceColumn": "ast_alt_ratio_delta",
            "lineageTag": "9a149185-77e8-469a-bff0-ab9ab21fb98e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_alt_ratio_pct_change",
            "dataType": "double",
            "sourceColumn": "ast_alt_ratio_pct_change",
            "lineageTag": "35e328e4-61f2-4ca2-bb88-52d9519adb77",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ast_alt_ratio_rolling3",
            "dataType": "double",
            "sourceColumn": "ast_alt_ratio_rolling3",
            "lineageTag": "c0122fbc-ef36-4011-a5f9-d60ca57d7662",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "indirect_bilirubin_prev",
            "dataType": "double",
            "sourceColumn": "indirect_bilirubin_prev",
            "lineageTag": "5a77acca-2e4f-4f0a-8030-e961da7d72b6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "indirect_bilirubin_delta",
            "dataType": "double",
            "sourceColumn": "indirect_bilirubin_delta",
            "lineageTag": "47892647-0151-4eac-a158-b5050c22eb18",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "indirect_bilirubin_pct_change",
            "dataType": "double",
            "sourceColumn": "indirect_bilirubin_pct_change",
            "lineageTag": "ffbb08ff-b883-4074-85f7-99ee02a42902",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "indirect_bilirubin_rolling3",
            "dataType": "double",
            "sourceColumn": "indirect_bilirubin_rolling3",
            "lineageTag": "ac1b580e-14dd-408c-a0d8-7c6dbbbc67a4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_total_bilirubin_pct_prev",
            "dataType": "double",
            "sourceColumn": "direct_total_bilirubin_pct_prev",
            "lineageTag": "7b46aa6e-8e98-4576-88c2-04be624b6b23",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_total_bilirubin_pct_delta",
            "dataType": "double",
            "sourceColumn": "direct_total_bilirubin_pct_delta",
            "lineageTag": "e036b9cb-ec5d-41ff-8d21-0f42603c50da",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_total_bilirubin_pct_pct_change",
            "dataType": "double",
            "sourceColumn": "direct_total_bilirubin_pct_pct_change",
            "lineageTag": "72fc0f28-9d74-4e2a-8a17-86d359399166",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "direct_total_bilirubin_pct_rolling3",
            "dataType": "double",
            "sourceColumn": "direct_total_bilirubin_pct_rolling3",
            "lineageTag": "161b7253-d8b7-4c62-b4db-007e3587df99",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "has_core_liver",
            "dataType": "double",
            "sourceColumn": "has_core_liver",
            "lineageTag": "cf6ab1d4-e3ad-4abe-8e72-ee2df66c7eca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "is_complete_profile",
            "dataType": "double",
            "sourceColumn": "is_complete_profile",
            "lineageTag": "f4edb936-9849-476e-b1ca-fcf429fe090d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "record_quality_note",
            "dataType": "string",
            "sourceColumn": "record_quality_note",
            "lineageTag": "48eb0a39-c588-4023-ad3b-4a6e532a03b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact_LiverMetrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Odbc.DataSource(\"dsn=bllod_raw\", [HierarchicalNavigation=true]),",
                "    liver_metrics_Table = Source{[Name=\"liver_metrics\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(liver_metrics_Table,{{\"exam_date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Trend View",
        "description": "Switches selected measures between current, previous, delta, delta %, and rolling 3 average views.",
        "lineageTag": "138c8482-84a0-4279-9702-70bc4c950302",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Current",
              "description": "Shows the selected measure as-is.",
              "expression": "SELECTEDMEASURE()",
              "ordinal": 0,
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              }
            },
            {
              "name": "Previous",
              "description": "Shows previous value for supported latest measures.",
              "expression": [
                "SWITCH(TRUE(),",
                "    ISSELECTEDMEASURE([Lipid Latest Total Cholesterol]), [Lipid Previous Total Cholesterol],",
                "    ISSELECTEDMEASURE([Lipid Latest HDL]), [Lipid Previous HDL],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL Final]), [Lipid Previous LDL Final],",
                "    ISSELECTEDMEASURE([Lipid Latest TG]), [Lipid Previous TG],",
                "    ISSELECTEDMEASURE([Lipid Latest Non-HDL]), [Lipid Previous Non-HDL],",
                "    ISSELECTEDMEASURE([Lipid Latest TC/HDL]), [Lipid Previous TC/HDL],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL/HDL]), [Lipid Previous LDL/HDL],",
                "    ISSELECTEDMEASURE([Lipid Latest TG/HDL]), [Lipid Previous TG/HDL],",
                "    ISSELECTEDMEASURE([Lipid Latest AIP]), [Lipid Previous AIP],",
                "    ISSELECTEDMEASURE([Lipid Latest Remnant]), [Lipid Previous Remnant],",
                "    ISSELECTEDMEASURE([Lipid Latest Lp(a)]), [Lipid Previous Lp(a)],",
                "    ISSELECTEDMEASURE([Endo Latest Glucose]), [Endo Previous Glucose],",
                "    ISSELECTEDMEASURE([Endo Latest Fasting Insulin]), [Endo Previous Fasting Insulin],",
                "    ISSELECTEDMEASURE([Endo Latest HbA1c]), [Endo Previous HbA1c],",
                "    ISSELECTEDMEASURE([Endo Latest eAG]), [Endo Previous eAG],",
                "    ISSELECTEDMEASURE([Endo Latest HOMA-IR]), [Endo Previous HOMA-IR],",
                "    ISSELECTEDMEASURE([Endo Latest QUICKI]), [Endo Previous QUICKI],",
                "    ISSELECTEDMEASURE([Endo Latest TSH]), [Endo Previous TSH],",
                "    ISSELECTEDMEASURE([Endo Latest Free T4]), [Endo Previous Free T4],",
                "    ISSELECTEDMEASURE([Endo Latest TSH/Free T4 Ratio]), [Endo Previous TSH/Free T4 Ratio],",
                "    ISSELECTEDMEASURE([Endo Latest Vitamin D]), [Endo Previous Vitamin D],",
                "    SELECTEDMEASURE()",
                ")"
              ],
              "ordinal": 1,
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              }
            },
            {
              "name": "Delta",
              "description": "Shows delta for supported latest measures.",
              "expression": [
                "SWITCH(TRUE(),",
                "    ISSELECTEDMEASURE([Lipid Latest Total Cholesterol]), [Lipid Total Cholesterol Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest HDL]), [Lipid HDL Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL Final]), [Lipid LDL Final Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest TG]), [Lipid TG Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest Non-HDL]), [Lipid Non-HDL Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest TC/HDL]), [Lipid TC/HDL Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL/HDL]), [Lipid LDL/HDL Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest TG/HDL]), [Lipid TG/HDL Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest AIP]), [Lipid AIP Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest Remnant]), [Lipid Remnant Delta],",
                "    ISSELECTEDMEASURE([Lipid Latest Lp(a)]), [Lipid Lp(a) Delta],",
                "    ISSELECTEDMEASURE([Endo Latest Glucose]), [Endo Glucose Delta],",
                "    ISSELECTEDMEASURE([Endo Latest Fasting Insulin]), [Endo Fasting Insulin Delta],",
                "    ISSELECTEDMEASURE([Endo Latest HbA1c]), [Endo HbA1c Delta],",
                "    ISSELECTEDMEASURE([Endo Latest eAG]), [Endo eAG Delta],",
                "    ISSELECTEDMEASURE([Endo Latest HOMA-IR]), [Endo HOMA-IR Delta],",
                "    ISSELECTEDMEASURE([Endo Latest QUICKI]), [Endo QUICKI Delta],",
                "    ISSELECTEDMEASURE([Endo Latest TSH]), [Endo TSH Delta],",
                "    ISSELECTEDMEASURE([Endo Latest Free T4]), [Endo Free T4 Delta],",
                "    ISSELECTEDMEASURE([Endo Latest TSH/Free T4 Ratio]), [Endo TSH/Free T4 Ratio Delta],",
                "    ISSELECTEDMEASURE([Endo Latest Vitamin D]), [Endo Vitamin D Delta],",
                "    SELECTEDMEASURE()",
                ")"
              ],
              "ordinal": 2,
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              }
            },
            {
              "name": "Delta %",
              "description": "Shows delta percent for supported latest measures.",
              "expression": [
                "SWITCH(TRUE(),",
                "    ISSELECTEDMEASURE([Lipid Latest Total Cholesterol]), [Lipid Total Cholesterol Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest HDL]), [Lipid HDL Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL Final]), [Lipid LDL Final Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest TG]), [Lipid TG Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest Non-HDL]), [Lipid Non-HDL Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest TC/HDL]), [Lipid TC/HDL Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL/HDL]), [Lipid LDL/HDL Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest TG/HDL]), [Lipid TG/HDL Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest AIP]), [Lipid AIP Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest Remnant]), [Lipid Remnant Delta %],",
                "    ISSELECTEDMEASURE([Lipid Latest Lp(a)]), [Lipid Lp(a) Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest Glucose]), [Endo Glucose Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest Fasting Insulin]), [Endo Fasting Insulin Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest HbA1c]), [Endo HbA1c Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest eAG]), [Endo eAG Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest HOMA-IR]), [Endo HOMA-IR Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest QUICKI]), [Endo QUICKI Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest TSH]), [Endo TSH Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest Free T4]), [Endo Free T4 Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest TSH/Free T4 Ratio]), [Endo TSH/Free T4 Ratio Delta %],",
                "    ISSELECTEDMEASURE([Endo Latest Vitamin D]), [Endo Vitamin D Delta %],",
                "    SELECTEDMEASURE()",
                ")"
              ],
              "ordinal": 3,
              "formatStringDefinition": {
                "expression": "\"0.00%;-0.00%;0.00%\""
              }
            },
            {
              "name": "Rolling 3 Avg",
              "description": "Shows rolling 3 average for supported latest measures.",
              "expression": [
                "SWITCH(TRUE(),",
                "    ISSELECTEDMEASURE([Lipid Latest Total Cholesterol]), [Lipid Total Cholesterol Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest HDL]), [Lipid HDL Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest LDL Final]), [Lipid LDL Final Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest TG]), [Lipid TG Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest Non-HDL]), [Lipid Non-HDL Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest AIP]), [Lipid AIP Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest TG/HDL]), [Lipid TG/HDL Rolling 3],",
                "    ISSELECTEDMEASURE([Lipid Latest Remnant]), [Lipid Remnant Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest Glucose]), [Endo Glucose Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest Fasting Insulin]), [Endo Fasting Insulin Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest HbA1c]), [Endo HbA1c Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest eAG]), [Endo eAG Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest HOMA-IR]), [Endo HOMA-IR Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest QUICKI]), [Endo QUICKI Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest TSH]), [Endo TSH Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest Free T4]), [Endo Free T4 Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest TSH/Free T4 Ratio]), [Endo TSH/Free T4 Ratio Rolling 3],",
                "    ISSELECTEDMEASURE([Endo Latest Vitamin D]), [Endo Vitamin D Rolling 3],",
                "    SELECTEDMEASURE()",
                ")"
              ],
              "ordinal": 4,
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              }
            }
          ]
        },
        "columns": [
          {
            "name": "Trend View",
            "dataType": "string",
            "description": "Trend calculation selector",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "0b23af7c-985e-4ae1-8e31-444f8be30169"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "e3945547-0b21-4d87-841a-bc90f13ce87a"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "IntendedPrecedence",
            "value": "20"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "d634f6ba-71a7-a5f1-93e3-29435b47df11",
        "fromTable": "Fact_EndoMetrics",
        "fromColumn": "exam_date",
        "toTable": "Dim_Date",
        "toColumn": "Date"
      },
      {
        "name": "834b8587-3723-8d65-d811-5e7e8b58bd4f",
        "fromTable": "Fact_LipidMetrics",
        "fromColumn": "exam_date",
        "toTable": "Dim_Date",
        "toColumn": "Date"
      },
      {
        "name": "58428610-86f2-a1d5-8a3d-224690c3a121",
        "fromTable": "Fact_LiverMetrics",
        "fromColumn": "exam_date",
        "toTable": "Dim_Date",
        "toColumn": "Date"
      }
    ],
    "cultures": [
      {
        "name": "en-US"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact_EndoMetrics\",\"Fact_LipidMetrics\",\"Fact_LiverMetrics\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  },
  "name": "SemanticModel"
}