table 'Measures 1'
	lineageTag: 31027062-531b-4a29-87c9-b55e1e6e3d35

	measure 'Measurement Count' = COUNTROWS('vw_fact_measurements')
		formatString: #,0
		displayFolder: Counts
		lineageTag: d07d8a23-a90d-4a0d-a892-d9a5ee5a24c0

	measure 'Alert Count' = COUNTROWS('vw_fact_alerts')
		formatString: #,0
		displayFolder: Counts
		lineageTag: 1ec969cb-a98e-4166-87c6-74c34bf9889d

	measure 'Anomaly Count' = COUNTROWS('vw_fact_anomalies')
		formatString: #,0
		displayFolder: Counts
		lineageTag: c3aaa639-ef02-4470-aa99-a7b4ff2dc224

	measure 'Latest Measurement Date' = MAX('vw_fact_measurements'[measurement_date])
		formatString: yyyy-mm-dd
		displayFolder: Dates
		lineageTag: 834679bb-37cc-4dd2-b305-ab47ccba15bb

	measure 'Avg RMSSD' = AVERAGE('vw_fact_measurements'[rmssd])
		formatString: 0.00
		displayFolder: Averages
		lineageTag: a13a84e1-1082-452b-85fa-34546b1451fd

	measure 'Avg SDNN' = AVERAGE('vw_fact_measurements'[sdnn])
		formatString: 0.00
		displayFolder: Averages
		lineageTag: 60d16911-026f-4da4-b42d-34224f76d533

	measure 'Avg HF' = AVERAGE('vw_fact_measurements'[HF])
		formatString: 0.00
		displayFolder: Averages
		lineageTag: a94292de-3f61-4e5f-b87b-4521c90aae6c

	measure 'Avg LF' = AVERAGE('vw_fact_measurements'[LF])
		formatString: 0.00
		displayFolder: Averages
		lineageTag: d7dbd4dd-6e57-4319-af13-e5400973a4ae

	measure 'Latest MS Score' = MAX('vw_latest_trends_by_source_metric'[latest_ms_score])
		formatString: 0.00
		displayFolder: Current
		lineageTag: 3751a12a-ad58-4271-beb8-a5390f8f1f42

	measure 'Latest Metric Value' =
			VAR LastDate = MAX('vw_long_measurements'[measurement_date])
			RETURN
			CALCULATE(
			    AVERAGE('vw_long_measurements'[value]),
			    'vw_long_measurements'[measurement_date] = LastDate
			)
		formatString: 0.00
		displayFolder: Current
		lineageTag: 7ca823ee-ab09-4768-9d61-8e5b0f6b4292

	measure 'Baseline Avg' =
			VAR m = SELECTEDVALUE('vw_long_measurements'[metric])
			RETURN
			SWITCH(
			    TRUE(),
			    m = "SD1", MAX('vw_latest_baseline_by_source'[avg_SD1]),
			    m = "SD2", MAX('vw_latest_baseline_by_source'[avg_SD2]),
			    m = "sdnn", MAX('vw_latest_baseline_by_source'[avg_sdnn]),
			    m = "rmssd", MAX('vw_latest_baseline_by_source'[avg_rmssd]),
			    m = "pNN50", MAX('vw_latest_baseline_by_source'[avg_pNN50]),
			    m = "VLF", MAX('vw_latest_baseline_by_source'[avg_VLF]),
			    m = "LF", MAX('vw_latest_baseline_by_source'[avg_LF]),
			    m = "HF", MAX('vw_latest_baseline_by_source'[avg_HF]),
			    BLANK()
			)
		formatString: 0.00
		displayFolder: Baseline
		lineageTag: f2e63ef6-5ff8-40b0-b793-d190ff121d22

	measure 'Baseline Std' =
			VAR m = SELECTEDVALUE('vw_long_measurements'[metric])
			RETURN
			SWITCH(
			    TRUE(),
			    m = "SD1", MAX('vw_latest_baseline_by_source'[std_SD1]),
			    m = "SD2", MAX('vw_latest_baseline_by_source'[std_SD2]),
			    m = "sdnn", MAX('vw_latest_baseline_by_source'[std_sdnn]),
			    m = "rmssd", MAX('vw_latest_baseline_by_source'[std_rmssd]),
			    m = "pNN50", MAX('vw_latest_baseline_by_source'[std_pNN50]),
			    m = "VLF", MAX('vw_latest_baseline_by_source'[std_VLF]),
			    m = "LF", MAX('vw_latest_baseline_by_source'[std_LF]),
			    m = "HF", MAX('vw_latest_baseline_by_source'[std_HF]),
			    BLANK()
			)
		formatString: 0.00
		displayFolder: Baseline
		lineageTag: b70aa86f-2236-4a33-978d-f53ad2b694f6

	measure 'Deviation vs Baseline %' = DIVIDE([Latest Metric Value] - [Baseline Avg], [Baseline Avg])
		formatString: 0.00%
		displayFolder: Baseline
		lineageTag: f5e79a4a-2035-42da-a2d5-647c79039b0f

	measure 'Z Score vs Baseline' = DIVIDE([Latest Metric Value] - [Baseline Avg], [Baseline Std])
		formatString: 0.00
		displayFolder: Baseline
		lineageTag: 83e7285f-9c5d-4300-8b1e-2e4139f060cc

	measure 'Trend Slope' = MAX('vw_latest_trends_by_source_metric'[slope])
		formatString: 0.0000
		displayFolder: Trend
		lineageTag: 82afe5b1-ff7e-4b4a-a98e-945105d8f37f

	measure 'Trend R Value' = MAX('vw_latest_trends_by_source_metric'[r_value])
		formatString: 0.0000
		displayFolder: Trend
		lineageTag: 5bcca82a-1004-4756-a53d-135f180626a5

	measure 'Trend Direction' = SELECTEDVALUE('vw_latest_trends_by_source_metric'[trend_direction])
		displayFolder: Trend
		lineageTag: 4646f19e-556e-4f4d-9615-1dcc8e9a46a5

	measure 'Trend Strength' = SELECTEDVALUE('vw_latest_trends_by_source_metric'[trend_strength])
		displayFolder: Trend
		lineageTag: 7cc6aa0c-8f2f-49ec-a94e-93a68ebe425f

	measure 'RMSSD 7D Avg' =
			AVERAGEX(
			    DATESINPERIOD('vw_dim_date'[date_key], MAX('vw_dim_date'[date_key]), -7, DAY),
			    CALCULATE(AVERAGE('vw_fact_measurements'[rmssd]))
			)
		formatString: 0.00
		displayFolder: Rolling 7D
		lineageTag: 4b577334-ae8b-4351-b8db-c1a305302b22

	measure 'SDNN 7D Avg' =
			AVERAGEX(
			    DATESINPERIOD('vw_dim_date'[date_key], MAX('vw_dim_date'[date_key]), -7, DAY),
			    CALCULATE(AVERAGE('vw_fact_measurements'[sdnn]))
			)
		formatString: 0.00
		displayFolder: Rolling 7D
		lineageTag: 726200f4-c027-4b12-9a49-2280042d6ea5

	measure 'MS Score 7D Avg' =
			AVERAGEX(
			    DATESINPERIOD('vw_dim_date'[date_key], MAX('vw_dim_date'[date_key]), -7, DAY),
			    CALCULATE(MAX('vw_latest_trends_by_source_metric'[latest_ms_score]))
			)
		formatString: 0.00
		displayFolder: Rolling 7D
		lineageTag: 046ed366-0174-4f59-a70d-570b18d52f30

	measure 'Has Alerts' = IF([Alert Count] > 0, "Yes", "No")
		displayFolder: Flags
		lineageTag: f9215a09-351b-47ce-bdec-a40408e96352

	measure 'Has Anomalies' = IF([Anomaly Count] > 0, "Yes", "No")
		displayFolder: Flags
		lineageTag: 689d73cf-179f-4a06-90f8-86dce214d02b

	column Dummy
		lineageTag: 0b20ef9a-41fc-41e1-9766-9d99c18b627d
		isNameInferred
		sourceColumn: [Dummy]

	partition 'Measures 1' = calculated
		mode: import
		source = ROW("Dummy", 1)

